#################################################################
# #   Copyright (c) 2007 Zenoss, Inc. All rights reserved.
#
#################################################################

__doc__='''

Add menu relations to all device organizers, OsProcesses, Services, etc
Add default menus to dmd and device organizers

$Id:$
'''
import Migrate
import os
from Products.ZenRelations.ImportRM import ImportRM
from Products.ZenModel.DeviceClass import DeviceClass
from Products.ZenModel.Device import Device

zenhome = os.environ['ZENHOME']
menuxml = os.path.join(zenhome, "Products/ZenModel/data/menus.xml")

class MenuRelations(Migrate.Step):
    version = Migrate.Version(1, 2, 0)

    def cutover(self, dmd):
        dmd.buildRelations()
#        for dev in dmd.Devices.getSubDevices():
#            dev.buildRelations()
#        for name in ['Devices', 'Systems', 'Groups', 'Locations',
#                        'Services', 'Processes']:
#            top = getattr(dmd, name)
#            orgs = top.getSubOrganizers()
#            orgs.insert(0, top)
#            for o in orgs:
#                o.buildRelations()
#                if name == 'Devices':
#                    for d in o.devices():
#                        d.buildRelations()
#                        if getattr(d, 'os', None):
#                            for n in ['ipservices', 'winservices', 'processes']:
#                                for p in getattr(d.os, n)():
#                                    p.buildRelations()
#                if name == 'Services':
#                    for sc in o.serviceclasses():
#                        sc.buildRelations()
#                if name == 'Processes':
#                    for pc in o.osProcessClasses():
#                        pc.buildRelations()

        # Add menus.
        
# Get rid of all menus

        dmd.zenMenus.removeRelation()
        dmd.Devices.zenMenus.removeRelation()
        dmd.Networks.zenMenus.removeRelation()

        dmd.buildMenus(
            {'Tabs':[
{'action': 'eventLog',
  'allowed_classes': ['BetterEventDetail'],
  'description': 'Log',
  'id': 'eventLog',
  'permissions': ('View',)},
 {'action': 'editSettings',
  'allowed_classes': ['DataRoot'],
  'description': 'Settings',
  'id': 'editSettings',
  'permissions': ('Manage DMD',)},
 {'action': 'viewNetworkOverview',
  'allowed_classes': ['IpNetwork'],
  'description': 'Overview',
  'id': 'viewNetworkOverview',
  'permissions': ('View',)},
 {'action': 'zenossInfo',
  'allowed_classes': ['ZenossInfo'],
  'description': 'Status',
  'id': 'zenossInfo',
  'permissions': ('Manage DMD',)},
 {'action': 'objRRDTemplate',
  'allowed_classes': ['Device',
                      'FileSystem',
                      'HardDisk',
                      'IpInterface',
                      'OSProcess'],
  'description': 'PerfConf',
  'id': 'objRRDTemplate',
  'permissions': ('Change Device',)},
 {'action': 'editStatusMonitorConf',
  'allowed_classes': ['StatusMonitorConf'],
  'description': 'Edit',
  'id': 'editStatusMonitorConf',
  'permissions': ('Manage DMD',)},
 {'action': 'viewHistory',
  'allowed_classes': ['Classifier',
                      'CPU',
                      'DataRoot',
                      'DeviceOrganizer',
                      'Device',
                      'DeviceClass',
                      'ExpansionCard',
                      'FileSystem',
                      'HardDisk',
                      'IpInterface',
                      'IpNetwork',
                      'IpServiceClass',
                      'IpService',
                      'MaintenanceWindow',
                      'Manufacturer',
                      'ManufacturerRoot',
                      'MibModule',
                      'MibNode',
                      'MibNotification',
                      'MibOrganizer',
                      'NagiosCmd',
                      'NagiosTemplate',
                      'OSProcessClass',
                      'OSProcessOrganizer',
                      'OSProcess',
                      'PerformanceConf',
                      'ProductClass',
                      'ServiceClass',
                      'ServiceOrganizer',
                      'Software',
                      'StatusMonitorConf',
                      'System',
                      'UserCommand',
                      'WinService',
                      'ActionRuleWindow',
                      'EventClassPropertyMixin',
                      'EventClass',
                      'EventManagerBase'],
  'description': 'Changes',
  'id': 'viewHistory',
  'permissions': ('View',)},
 {'action': 'actionRuleWindowDetail',
  'allowed_classes': ['ActionRuleWindow'],
  'description': 'Status',
  'id': 'actionRuleWindowDetail',
  'permissions': ('View',)},
 {'action': 'deviceCustomEdit',
  'allowed_classes': ['Device'],
  'description': 'Custom',
  'id': 'deviceCustomEdit',
  'permissions': ('View',)},
 {'action': 'viewCPU',
  'allowed_classes': ['CPU'],
  'description': 'Status',
  'id': 'viewCPU',
  'permissions': ('View',)},
 {'action': 'editEventManagerHistoryFields',
  'allowed_classes': ['EventManagerBase'],
  'description': 'History Fields',
  'id': 'editEventManagerHistoryFields',
  'permissions': ('Manage DMD',)},
 {'action': 'editRRDDataSource',
  'allowed_classes': ['RRDDataSourceError'],
  'description': 'Data Source',
  'id': 'editRRDDataSource',
  'permissions': ('View',)},
 {'action': 'viewDevicePerformance',
  'allowed_classes': ['Device'],
  'description': 'Perf',
  'id': 'viewDevicePerformance',
  'permissions': ('View',)},
 {'action': 'zenossVersions',
  'allowed_classes': ['ZenossInfo'],
  'description': 'Versions',
  'id': 'zenossVersions',
  'permissions': ('Manage DMD',)},
 {'action': 'eventClassInstEdit',
  'allowed_classes': ['EventClassPropertyMixin'],
  'description': 'Edit',
  'id': 'eventClassInstEdit',
  'permissions': ('Manage DMD',)},
 {'action': 'deviceHardwareDetail',
  'allowed_classes': ['Device'],
  'description': 'Hardware',
  'id': 'deviceHardwareDetail',
  'permissions': ('View',)},
 {'action': 'editEventCommand',
  'allowed_classes': ['EventCommand'],
  'description': 'Edit',
  'id': 'editEventCommand',
  'permissions': ('Manage DMD',)},
 {'action': 'viewDeviceReport',
  'allowed_classes': ['DeviceReport'],
  'description': 'Report',
  'id': 'viewDeviceReport',
  'permissions': ('View',)},
 {'action': 'viewHistoryEvents',
  'allowed_classes': ['DeviceClass',
                      'DeviceOrganizer',
                      'Device',
                      'System',
                      'EventClassPropertyMixin',
                      'EventClass'],
  'description': 'History',
  'id': 'viewHistoryEvents',
  'permissions': ('View',)},
 {'action': 'ipServiceClassEdit',
  'allowed_classes': ['IpServiceClass'],
  'description': 'Edit',
  'id': 'ipServiceClassEdit',
  'permissions': ('Manage DMD',)},
 {'action': 'eventClassStatus',
  'allowed_classes': ['EventClass'],
  'description': 'Classes',
  'id': 'eventClassStatus',
  'permissions': ('View',)},
 {'action': 'deviceManagement',
  'allowed_classes': ['Device'],
  'description': 'Manage',
  'id': 'deviceManagement',
  'permissions': ('Change Device',)},
 {'action': 'viewExpansionCard',
  'allowed_classes': ['ExpansionCard'],
  'description': 'Status',
  'id': 'viewExpansionCard',
  'permissions': ('View',)},
 {'action': 'serviceOrganizerManage',
  'allowed_classes': ['ServiceOrganizer'],
  'description': 'Manage',
  'id': 'serviceOrganizerManage',
  'permissions': ('Manage DMD',)},
 {'action': 'deviceStatus',
  'allowed_classes': ['Device'],
  'description': 'Status',
  'id': 'deviceStatus',
  'permissions': ('View',)},
 {'action': 'osProcessOrganizerManage',
  'allowed_classes': ['OSProcessOrganizer'],
  'description': 'Manage',
  'id': 'osProcessOrganizerManage',
  'permissions': ('Manage DMD',)},
 {'action': 'viewSystemPerformance',
  'allowed_classes': ['System'],
  'description': 'Performance',
  'id': 'viewSystemPerformance',
  'permissions': ('View',)},
 {'action': 'viewSoftwareOverview',
  'allowed_classes': ['Software'],
  'description': 'Overview',
  'id': 'viewSoftwareOverview',
  'permissions': ('View',)},
 {'action': 'zenossConfigs',
  'allowed_classes': ['ZenossInfo'],
  'description': 'Configuration',
  'id': 'zenossConfigs',
  'permissions': ('Manage DMD',)},
 {'action': 'ipServiceClassStatus',
  'allowed_classes': ['IpServiceClass'],
  'description': 'Status',
  'id': 'ipServiceClassStatus',
  'permissions': ('View',)},
 {'action': 'deviceOsDetail',
  'allowed_classes': ['Device'],
  'description': 'OS',
  'id': 'deviceOsDetail',
  'permissions': ('View',)},
 {'action': 'eventClassInstStatus',
  'allowed_classes': ['EventClassPropertyMixin'],
  'description': 'Status',
  'id': 'eventClassInstStatus',
  'permissions': ('View',)},
 {'action': 'ipServiceClassManage',
  'allowed_classes': ['IpServiceClass'],
  'description': 'Manage',
  'id': 'ipServiceClassManage',
  'permissions': ('Manage DMD',)},
 {'action': 'viewMibNotification',
  'allowed_classes': ['MibNotification'],
  'description': 'Overview',
  'id': 'viewMibNotification',
  'permissions': ('View',)},
 {'action': 'editManufacturer',
  'allowed_classes': ['Manufacturer'],
  'description': 'Edit',
  'id': 'editManufacturer',
  'permissions': ('Manage DMD',)},
 {'action': 'editActionRuleMessage',
  'allowed_classes': ['ActionRule'],
  'description': 'Message',
  'id': 'editActionRuleMessage',
  'permissions': ('Change Settings',)},
 {'action': 'addDevice',
  'allowed_classes': ['ZDeviceLoader'],
  'description': 'Status',
  'id': 'addDevice',
  'permissions': ('View',)},
 {'action': 'maintenanceWindowDetail',
  'allowed_classes': ['MaintenanceWindow'],
  'description': 'Status',
  'id': 'maintenanceWindowDetail',
  'permissions': ('View',)},
 {'action': 'mibOrganizerOverview',
  'allowed_classes': ['MibOrganizer'],
  'description': 'Overview',
  'id': 'mibOrganizerOverview',
  'permissions': ('View',)},
 {'action': 'serviceClassStatus',
  'allowed_classes': ['ServiceClass'],
  'description': 'Status',
  'id': 'serviceClassStatus',
  'permissions': ('View',)},
 {'action': 'viewFileSystem',
  'allowed_classes': ['FileSystem'],
  'description': 'Status',
  'id': 'viewFileSystem',
  'permissions': ('View',)},
 {'action': 'editRRDDataPoint',
  'allowed_classes': ['RRDDataPointError'],
  'description': 'Data Point',
  'id': 'editRRDDataPoint',
  'permissions': ('View',)},
 {'action': 'viewEvents',
  'allowed_classes': ['DeviceClass',
                      'DeviceOrganizer',
                      'Device',
                      'System',
                      'EventClassPropertyMixin',
                      'EventClass'],
  'description': 'Events',
  'id': 'viewEvents',
  'permissions': ('View',)},
 {'action': 'viewMibModule',
  'allowed_classes': ['MibModule'],
  'description': 'Overview',
  'id': 'viewMibModule',
  'permissions': ('View',)},
 {'action': 'editEventManager',
  'allowed_classes': ['EventManagerBase'],
  'description': 'Edit',
  'id': 'editEventManager',
  'permissions': ('Manage DMD',)},
 {'action': 'viewManufacturers',
  'allowed_classes': ['ManufacturerRoot'],
  'description': 'Overview',
  'id': 'viewManufacturers',
  'permissions': ('View',)},
 {'action': 'osProcessManage',
  'allowed_classes': ['OSProcess'],
  'description': 'Manage',
  'id': 'osProcessManage',
  'permissions': ('Manage DMD',)},
 {'action': 'editNagiosCmd',
  'allowed_classes': ['NagiosCmd'],
  'description': 'Nagios Command',
  'id': 'editNagiosCmd',
  'permissions': ('View',)},
 {'action': 'serviceClassManage',
  'allowed_classes': ['ServiceClass'],
  'description': 'Manage',
  'id': 'serviceClassManage',
  'permissions': ('Manage DMD',)},
 {'action': 'editPerformanceConf',
  'allowed_classes': ['PerformanceConf'],
  'description': 'Edit',
  'id': 'editPerformanceConf',
  'permissions': ('Manage DMD',)},
 {'action': 'viewPackDetail',
  'allowed_classes': ['ZenPack'],
  'description': 'Detail',
  'id': 'viewPackDetail',
  'permissions': ('Manage DMD',)},
 {'action': 'ipServiceManage',
  'allowed_classes': ['IpService'],
  'description': 'Manage',
  'id': 'ipServiceManage',
  'permissions': ('Manage DMD',)},
 {'action': 'viewHardDisk',
  'allowed_classes': ['HardDisk'],
  'description': 'Status',
  'id': 'viewHardDisk',
  'permissions': ('View',)},
 {'action': 'editEventManagerFields',
  'allowed_classes': ['EventManagerBase'],
  'description': 'Fields',
  'id': 'editEventManagerFields',
  'permissions': ('Manage DMD',)},
 {'action': 'userCommandDetail',
  'allowed_classes': ['UserCommand'],
  'description': 'User Command',
  'id': 'userCommandDetail',
  'permissions': ('View',)},
 {'action': 'editProductClass',
  'allowed_classes': ['ProductClass'],
  'description': 'Edit',
  'id': 'editProductClass',
  'permissions': ('Manage DMD',)},
 {'action': 'viewZenPacks',
  'allowed_classes': ['ZenossInfo'],
  'description': 'ZenPacks',
  'id': 'viewZenPacks',
  'permissions': ('Manage DMD',)},
 {'action': 'editMibModule',
  'allowed_classes': ['MibModule'],
  'description': 'Edit',
  'id': 'editMibModule',
  'permissions': ('View',)},
 {'action': 'deviceList',
  'allowed_classes': ['DeviceClass'],
  'description': 'Devices',
  'id': 'deviceList',
  'permissions': ('View',)},
 {'action': 'viewIpAddressOverview',
  'allowed_classes': ['IpAddress'],
  'description': 'Overview',
  'id': 'viewIpAddressOverview',
  'permissions': ('View',)},
 {'action': 'viewPerformanceConfOverview',
  'allowed_classes': ['PerformanceConf'],
  'description': 'Overview',
  'id': 'viewPerformanceConfOverview',
  'permissions': ('View',)},
 {'action': 'deviceSoftwareDetail',
  'allowed_classes': ['Device'],
  'description': 'Software',
  'id': 'deviceSoftwareDetail',
  'permissions': ('View',)},
 {'action': 'editDeviceReport',
  'allowed_classes': ['DeviceReport'],
  'description': 'Edit',
  'id': 'editDeviceReport',
  'permissions': ('Manage DMD',)},
 {'action': 'osProcessClassManage',
  'allowed_classes': ['OSProcessClass'],
  'description': 'Manage',
  'id': 'osProcessClassManage',
  'permissions': ('Manage DMD',)},
 {'action': 'deviceOrganizerStatus',
  'allowed_classes': ['DeviceClass', 'DeviceOrganizer', 'System'],
  'description': 'Classes',
  'id': 'deviceOrganizerStatus',
  'permissions': ('View',)},
 {'action': 'viewManufacturerOverview',
  'allowed_classes': ['Manufacturer'],
  'description': 'Overview',
  'id': 'viewManufacturerOverview',
  'permissions': ('View',)},
 {'action': 'viewNagiosTemplate',
  'allowed_classes': ['NagiosTemplate'],
  'description': 'Nagios Config',
  'id': 'viewNagiosTemplate',
  'permissions': ('View',)},
 {'action': 'viewStatusMonitorOverview',
  'allowed_classes': ['StatusMonitorConf'],
  'description': 'Overview',
  'id': 'viewStatusMonitorOverview',
  'permissions': ('View',)},
 {'action': 'getEventView',
  'allowed_classes': ['CustomEventView'],
  'description': 'View',
  'id': 'getEventView',
  'permissions': ('View',)},
 {'action': 'ipServiceDetail',
  'allowed_classes': ['IpService'],
  'description': 'Status',
  'id': 'ipServiceDetail',
  'permissions': ('View',)},
 {'action': 'editRRDGraph',
  'allowed_classes': ['RRDGraph'],
  'description': 'Graph',
  'id': 'editRRDGraph',
  'permissions': ('View',)},
 {'action': 'deviceOrganizerManage',
  'allowed_classes': ['DeviceOrganizer', 'DeviceClass', 'System'],
  'description': 'Manage',
  'id': 'deviceOrganizerManage',
  'permissions': ('Manage DMD',)},
 {'action': 'editDevice',
  'allowed_classes': ['Device'],
  'description': 'Edit',
  'id': 'editDevice',
  'permissions': ('Change Device',)},
 {'action': 'editRRDThreshold',
  'allowed_classes': ['RRDThreshold'],
  'description': 'RRD Threshold',
  'id': 'editRRDThreshold',
  'permissions': ('View',)},
 {'action': 'osProcessClassStatus',
  'allowed_classes': ['OSProcessClass'],
  'description': 'Status',
  'id': 'osProcessClassStatus',
  'permissions': ('View',)},
 {'action': 'winServiceManage',
  'allowed_classes': ['WinService'],
  'description': 'Manage',
  'id': 'winServiceManage',
  'permissions': ('Manage DMD',)},
 {'action': 'dataRootManage',
  'allowed_classes': ['DataRoot'],
  'description': 'Manage',
  'id': 'dataRootManage',
  'permissions': ('Manage DMD',)},
 {'action': 'viewMibNode',
  'allowed_classes': ['MibNode'],
  'description': 'Overview',
  'id': 'viewMibNode',
  'permissions': ('View',)},
 {'action': 'eventClassInstSequence',
  'allowed_classes': ['EventClassPropertyMixin'],
  'description': 'Sequence',
  'id': 'eventClassInstSequence',
  'permissions': ('View',)},
 {'action': 'listEventCommands',
  'allowed_classes': ['EventManagerBase'],
  'description': 'Commands',
  'id': 'listEventCommands',
  'permissions': ('Manage DMD',)},
 {'action': 'viewEventLog',
  'allowed_classes': ['EventDetail'],
  'description': 'Log',
  'id': 'viewEventLog',
  'permissions': ('View',)},
 {'action': 'viewEventDetail',
  'allowed_classes': ['EventDetail'],
  'description': 'Details',
  'id': 'viewEventDetail',
  'permissions': ('View',)},
 {'action': 'manageClassifiers',
  'allowed_classes': ['Classifier'],
  'description': 'Overview',
  'id': 'manageClassifiers',
  'permissions': ('View',)},
 {'action': 'viewIpInterface',
  'allowed_classes': ['IpInterface'],
  'description': 'Status',
  'id': 'viewIpInterface',
  'permissions': ('View',)},
 {'action': 'viewEventFields',
  'allowed_classes': ['EventDetail'],
  'description': 'Fields',
  'id': 'viewEventFields',
  'permissions': ('View',)},
 {'action': 'editActionRuleSchedule',
  'allowed_classes': ['ActionRule'],
  'description': 'Schedule',
  'id': 'editActionRuleSchedule',
  'permissions': ('Change Settings',)},
 {'action': 'osProcessOrganizerOverview',
  'allowed_classes': ['OSProcessOrganizer'],
  'description': 'Classes',
  'id': 'osProcessOrganizerOverview',
  'permissions': ('View',)},
 {'action': 'serviceOrganizerOverview',
  'allowed_classes': ['ServiceOrganizer'],
  'description': 'Classes',
  'id': 'serviceOrganizerOverview',
  'permissions': ('View',)},
 {'action': 'eventMappingList',
  'allowed_classes': ['EventClass'],
  'description': 'Mappings',
  'id': 'eventMappingList',
  'permissions': ('View',)},
 {'action': 'eventFields',
  'allowed_classes': ['BetterEventDetail'],
  'description': 'Fields',
  'id': 'eventFields',
  'permissions': ('View',)},
 {'action': 'osProcessClassEdit',
  'allowed_classes': ['OSProcessClass'],
  'description': 'Edit',
  'id': 'osProcessClassEdit',
  'permissions': ('Manage DMD',)},
 {'action': 'editActionRule',
  'allowed_classes': ['ActionRule'],
  'description': 'Edit',
  'id': 'editActionRule',
  'permissions': ('Change Settings',)},
 {'action': 'monitorList',
  'allowed_classes': ['MonitorClass'],
  'description': 'View',
  'id': 'monitorList',
  'permissions': ('View',)},
 {'action': 'viewProductClassOverview',
  'allowed_classes': ['ProductClass'],
  'description': 'Overview',
  'id': 'viewProductClassOverview',
  'permissions': ('View',)},
 {'action': 'eventDetail',
  'allowed_classes': ['BetterEventDetail'],
  'description': 'Details',
  'id': 'eventDetail',
  'permissions': ('View',)},
 {'action': 'perfConfig',
  'allowed_classes': ['DeviceClass'],
  'description': 'Perf Config',
  'id': 'perfConfig',
  'permissions': ('Change Device',)},
 {'action': 'zPropertyEdit',
  'allowed_classes': ['Device',
                      'DeviceClass',
                      'IpNetwork',
                      'IpServiceClass',
                      'Manufacturer',
                      'OSProcessClass',
                      'OSProcessOrganizer',
                      'ProductClass',
                      'ServiceClass',
                      'ServiceOrganizer',
                      'EventClassPropertyMixin',
                      'EventClass'],
  'description': 'zProperties',
  'id': 'zPropertyEdit',
  'permissions': ('View',)},
 {'action': 'serviceClassEdit',
  'allowed_classes': ['ServiceClass'],
  'description': 'Edit',
  'id': 'serviceClassEdit',
  'permissions': ('Manage DMD',)},
 {'action': 'editEventView',
  'allowed_classes': ['CustomEventView'],
  'description': 'Edit',
  'id': 'editEventView',
  'permissions': ('Change Settings',)},
 {'action': 'viewRRDTemplate',
  'allowed_classes': ['ConfigurationError'],
  'description': 'Performance Template',
  'id': 'viewRRDTemplate',
  'permissions': ('View',)},
 {'action': 'viewReportClass',
  'allowed_classes': ['ReportClass'],
  'description': 'View',
  'id': 'viewReportClass',
  'permissions': ('View',)},
 {'action': 'winServiceDetail',
  'allowed_classes': ['WinService'],
  'description': 'Status',
  'id': 'winServiceDetail',
  'permissions': ('View',)},
 {'action': 'manageUserFolder',
  'allowed_classes': ['UserSettingsManager'],
  'description': 'Overview',
  'id': 'manageUserFolder',
  'permissions': ('View',)},
 {'action': 'osProcessDetail',
  'allowed_classes': ['OSProcess'],
  'description': 'Status',
  'id': 'osProcessDetail',
  'permissions': ('View',)}] ,

            'Device_list':[
                dict(
                    id=         'moveclass',
                    description='Move to Class...',
                    action=     'dialog_moveDevices',
                    permissions=('Change Device',)
                    ),
                dict(
                    id=         'setGroups',
                    description='Set Groups...',
                    action=     'dialog_setGroups',
                    permissions=('Change Device',)
                    ),
                dict(
                    id=         'setSystems',
                    description='Set Systems...',
                    action=     'dialog_setSystems',
                    permissions=('Change Device',)
                    ),
                dict(
                    id=         'setLocation',
                    description='Set Location...',
                    action=     'dialog_setLocation',
                    permissions=('Change Device',)
                    ),
                dict(
                    id=         'removeDevices',
                    description='Delete devices...',
                    action=     'dialog_removeDevices',
                    permissions=('Change Device',)
                    ),
                dict(
                    id=         'addToZenPack',
                    description='Add to ZenPack...',
                    action=     'dialog_addToZenPack',
                    permissions=('View',)
                    ),
                ],
            })


        dmd.Networks.buildMenus(
            {'Actions':[
                dict(
                    id=             'discover',
                    description=    'Discover Devices', 
                    action=         'discoverDevices', 
                    allowed_classes= ('IpNetwork',)
                    ),
                ]
            })
            
MenuRelations()
