# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python SMIDUMP03-MIB

FILENAME = "SMIDUMP03-MIB.mib"

MIB = {
    "moduleName" : "SMIDUMP03-MIB",

    "SMIDUMP03-MIB" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """Zenoss Inc.""",
        "contact" : 
            """EMail: dev@zenoss.com""",
        "description" :
            """This is a test MIB module.""",
        "revisions" : (
            {
                "date" : "2018-05-03 00:00",
                "description" :
                    """Initial version.""",
            },
        ),
        "identity node" : "smidump03",
    },

    "imports" : (
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "snmpModules"},
    ),

    "nodes" : {
        "smidump03" : {
            "nodetype" : "node",
            "moduleName" : "SMIDUMP03-MIB",
            "oid" : "1.3.6.1.6.3.503",
            "status" : "current",
        }, # node
    }, # nodes

}
