# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python SMIDUMP02-MIB

FILENAME = "multi.mib"

MIB = {
    "moduleName" : "SMIDUMP02-MIB",

    "SMIDUMP02-MIB" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """Zenoss Inc.""",
        "contact" : 
            """EMail: dev@zenoss.com""",
        "description" :
            """This is a test MIB module.""",
        "revisions" : (
            {
                "date" : "2018-05-03 00:00",
                "description" :
                    """Initial version.""",
            },
        ),
        "identity node" : "smidump02",
    },

    "imports" : (
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "snmpModules"},
    ),

    "nodes" : {
        "smidump02" : {
            "nodetype" : "node",
            "moduleName" : "SMIDUMP02-MIB",
            "oid" : "1.3.6.1.6.3.502",
            "status" : "current",
        }, # node
    }, # nodes

}
# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python SMIDUMP01-MIB

FILENAME = "multi.mib"

MIB = {
    "moduleName" : "SMIDUMP01-MIB",

    "SMIDUMP01-MIB" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """Zenoss Inc.""",
        "contact" : 
            """EMail: dev@zenoss.com""",
        "description" :
            """This is a test MIB module.""",
        "revisions" : (
            {
                "date" : "2018-05-03 00:00",
                "description" :
                    """Initial version.""",
            },
        ),
        "identity node" : "smidump01",
    },

    "imports" : (
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "NOTIFICATION-TYPE"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-TYPE"},
        {"module" : "SNMPv2-SMI", "name" : "Integer32"},
        {"module" : "SNMPv2-SMI", "name" : "snmpModules"},
    ),

    "nodes" : {
        "smidump01" : {
            "nodetype" : "node",
            "moduleName" : "SMIDUMP01-MIB",
            "oid" : "1.3.6.1.6.3.501",
            "status" : "current",
        }, # node
        "smidump01Notifications" : {
            "nodetype" : "node",
            "moduleName" : "SMIDUMP01-MIB",
            "oid" : "1.3.6.1.6.3.501.0",
        }, # node
        "smidump01Objects" : {
            "nodetype" : "node",
            "moduleName" : "SMIDUMP01-MIB",
            "oid" : "1.3.6.1.6.3.501.1",
        }, # node
        "dumpCount" : {
            "nodetype" : "scalar",
            "moduleName" : "SMIDUMP01-MIB",
            "oid" : "1.3.6.1.6.3.501.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "2147483647"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "2147483647"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The number of dumps thus far.""",
        }, # scalar
    }, # nodes

    "notifications" : {
        "smidump01Notification01" : {
            "nodetype" : "notification",
            "moduleName" : "SMIDUMP01-MIB",
            "oid" : "1.3.6.1.6.3.501.0.1",
            "status" : "current",
            "objects" : {
                "dumpCount" : {
                    "nodetype" : "object",
                    "module" : "SMIDUMP01-MIB"
                },
            },
            "description" :
                """A sample description.""",
        }, # notification
    }, # notifications

}
