#!/bin/bash

##############################################################################
# 
# Copyright (C) Zenoss, Inc. 2006, all rights reserved.
# 
# This content is made available according to terms specified in
# License.zenoss under the directory where your Zenoss product is installed.
# 
##############################################################################


#
# This script runs weekly and is reponsible for packing the ZODB
# database.  As objects are deleted their space is never reclaimed
# from the ZODB database until it is packed.  This script executes the
# Zenoss command to pack the database.
#

# location of the shell script that initializes the zenoss environment
ZENOSS_ENV=~zenoss/.bashrc

# print the error message passed and exit with a return code of 1 (error)
fail() {
    echo $*
    exit 1
}


#
# main script starts here
#

# set up the environment
test -f ${ZENOSS_ENV} || fail "Source environment not found"
. ${ZENOSS_ENV}

if [ -z "$ZOPEHOME" ] ; then
   ZOPEHOME="$ZENHOME"
fi
$ZOPEHOME/bin/zenossdbpack
