PingStatus = "/Status/Ping"
SnmpStatus = "/Status/Snmp"
HeartbeatStatus = "/Status/Heartbeat"
AppStart = "/App/Start"
AppStop = "/App/Stop"
DNSFail = "/App/DNS/Fail"
Heartbeat = "/Heartbeat"
Unknown = "/Unknown"
