name: prodbin-ci
services:
  rabbitmq:
    image: zenoss/rabbitmq:5ccc9e3
    command: ["/bin/supervisord", "-n", "-c", "/etc/rabbitmq/supervisord.conf"]
    healthcheck:
      test: runuser -u rabbitmq -- /opt/rabbitmq/sbin/listening
      interval: 30s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:r
      - ./rabbitmq/advanced.config:/etc/rabbitmq/advanced.config:r
      - ./rabbitmq/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf:r
      - ./rabbitmq/supervisord.conf:/etc/rabbitmq/supervisord.conf:r
    networks:
      - infra

  redis:
    image: redis:6.0
    command: /usr/local/bin/redis-server /etc/redis/redis.conf
    healthcheck:
      test: /usr/local/bin/redis-cli ping | grep -q PONG
      interval: 30s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
    volumes:
      - ./redis/:/etc/redis:r
    networks:
      - infra

  mariadb:
    image: mariadb:10.6
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=zenoss
      - MARIADB_PASSWORD=zenoss
      - MARIADB_DATABASE=zodb
    healthcheck:
      test: mysql --protocol TCP -uzenoss -hmariadb -pzenoss -e 'select 1'
      interval: 60s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
    volumes:
      - type: bind
        source: ./mariadb/initdb.d
        target: /docker-entrypoint-initdb.d
    networks:
      - infra

  solr:
    image: solr:9.6
    command: solr-precreate zenoss_model /zenoss_model
    healthcheck:
      test: curl -sI http://localhost:8983/solr/admin/cores | grep -q 200
      interval: 60s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
    environment:
      SOLR_HEAP: "1500m"
      SOLR_JETTY_HOST: "0.0.0.0"
      SOLR_SECURITY_MANAGER_ENABLED: "false"
      SOLR_OPTS: "-Dsolr.http1=true"
    volumes:
      - ./solr/zenoss_model/:/zenoss_model:r
    networks:
      - infra

  runtests:
    build:
      context: prodbin
    command: /usr/bin/bash --login /mnt/ci/runtests.sh
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      solr:
        condition: service_healthy
    volumes:
      - ../:/mnt:rw
      - ./prodbin/etc/global.conf:/opt/zenoss/etc/global.conf:r
      - ./prodbin/etc/zope.conf:/opt/zenoss/etc/zope.conf:r
      - ./prodbin/etc/zodb_db_main.conf:/opt/zenoss/etc/zodb_db_main.conf:r
    working_dir: /mnt
    networks:
      - infra

networks:
  infra:
