services:
  rabbitmq:
    image: zenoss/rabbitmq:5ccc9e3
    command: ["/bin/supervisord", "-n", "-c", "/etc/rabbitmq/supervisord.conf"]
    volumes:
      - type: bind
        source: ./rabbitmq/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
      - type: bind
        source: ./rabbitmq/advanced.config
        target: /etc/rabbitmq/advanced.config
      - type: bind
        source: ./rabbitmq/rabbitmq-env.conf
        target: /etc/rabbitmq/rabbitmq-env.conf
      - type: bind
        source: ./rabbitmq/supervisord.conf
        target: /etc/rabbitmq/supervisord.conf
    networks:
      - infra

  redis:
    image: zenoss/redis:760f98c
    command: ["/bin/supervisord", "-n", "-c", "/etc/redis/supervisord.conf"]
    volumes:
      - type: bind
        source: ./redis/redis.conf
        target: /etc/redis/redis.conf
      - type: bind
        source: ./redis/supervisord.conf
        target: /etc/redis/supervisord.conf
    networks:
      - infra

  memcached:
    image: zenoss/memcached:cc38f31
    command: ["/bin/supervisord", "-n", "-c", "/etc/memcached/supervisord.conf"]
    volumes:
      - type: bind
        source: ./memcached/memcached.conf
        target: /etc/memcached/memcached.conf
      - type: bind
        source: ./memcached/supervisord.conf
        target: /etc/memcached/supervisord.conf
    networks:
      - infra

  mariadb:
    image: mariadb:10.6
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=zenoss
      - MARIADB_PASSWORD=zenoss
      - MARIADB_DATABASE=zodb
    volumes:
      - type: bind
        source: ./mariadb/initdb.d
        target: /docker-entrypoint-initdb.d
    networks:
      - infra

  solr:
    image: solr:9.6
    command:
      - "solr"
      - "start"
      - "-f"
      - "-v"
      - "-cloud"
      - "-DzkRun"
      - "-DnumShards=1"
      - "-Dcollection.configName=zenoss_model"
      - "-Dsolr.jetty.request.header.size=1000000"
    healthcheck:
      test: curl -sI http://localhost:8983/solr/admin/cores | grep -q 200
      interval: 60s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
    volumes:
      - type: bind
        source: ./solr/zenoss_model/
        target: /opt/solr/server/solr/configsets/zenoss_model
      - type: bind
        source: ./solr/solr.in.sh
        target: /etc/default/solr.in.sh
    networks:
      - infra

  solr-init:
    image: solr:9.6
    command: 
      - "solr"
      - "create_collection"
      - "-c"
      - "zenoss_model"
      - "-d"
      - "/opt/solr/server/solr/configsets/zenoss_model"
      - "-n"
      - "zenoss_model"
      - "-p"
      - "8983"
    depends_on:
      solr:
        condition: service_healthy
        restart: true
    volumes:
      - type: bind
        source: ./solr/zenoss_model/
        target: /opt/solr/server/solr/configsets/zenoss_model
      - type: bind
        source: ./solr-init/solr.in.sh
        target: /etc/default/solr.in.sh
    networks:
      - infra

  prodbin-test:
    build:
      context: prodbin
    volumes:
      - type: bind
        source: ./prodbin/etc/global.conf
        target: /opt/zenoss/etc/global.conf
      - type: bind
        source: ./prodbin/etc/zope.conf
        target: /opt/zenoss/etc/zope.conf
      - type: bind
        source: ./prodbin/etc/zodb_db_main.conf
        target: /opt/zenoss/etc/zodb_db_main.conf
    networks:
      - infra

networks:
  infra: {}
