###########################################################################
#
# This program is part of Zenoss Core, an open source monitoring platform.
# Copyright (C) 2007, Zenoss Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published by
# the Free Software Foundation.
#
# For complete information please visit: http://www.zenoss.com/oss/
#
###########################################################################

import sys
import os
import time
import re
from socket import getfqdn
import pythoncom

from twisted.internet import reactor, defer

import Globals
from Products.ZenHub.PBDaemon import FakeRemote, PBDaemon as Base
from Products.ZenEvents.ZenEventClasses import \
     Heartbeat, App_Start, App_Stop, Clear, Warning
from Products.ZenUtils.Driver import drive, driveLater

from StatusTest import StatusTest
from WinServiceTest import WinServiceTest
from WinEventlog import WinEventlog

TIMEOUT_CODE = 2147209215
RPC_ERROR_CODE = 2147023170

ERROR_CODE_MAP = {
 '1001 ': ('ERROR_STACK_OVERFLOW',
           'Recursion too deep; the stack overflowed.'),
 '1002 ': ('ERROR_INVALID_MESSAGE',
           'The window cannot act on the sent message.'),
 '1003 ': ('ERROR_CAN_NOT_COMPLETE', 'Cannot complete this function.'),
 '1004 ': ('ERROR_INVALID_FLAGS', 'Invalid flags.'),
 '1005 ': ('ERROR_UNRECOGNIZED_VOLUME',
           'The volume does not contain a recognized file system. Please make sure that all required file system drivers are loaded and that the volume is not corrupted.'),
 '1006 ': ('ERROR_FILE_INVALID',
           'The volume for a file has been externally altered so that the opened file is no longer valid.'),
 '1007 ': ('ERROR_FULLSCREEN_MODE',
           'The requested operation cannot be performed in full-screen mode.'),
 '1008 ': ('ERROR_NO_TOKEN',
           'An attempt was made to reference a token that does not exist.'),
 '1009 ': ('ERROR_BADDB', 'The configuration registry database is corrupt.'),
 '1010 ': ('ERROR_BADKEY', 'The configuration registry key is invalid.'),
 '1011 ': ('ERROR_CANTOPEN',
           'The configuration registry key could not be opened.'),
 '1012 ': ('ERROR_CANTREAD',
           'The configuration registry key could not be read.'),
 '1013 ': ('ERROR_CANTWRITE',
           'The configuration registry key could not be written.'),
 '1014 ': ('ERROR_REGISTRY_RECOVERED',
           'One of the files in the registry database had to be recovered by use of a log or alternate copy. The recovery was successful.'),
 '1015 ': ('ERROR_REGISTRY_CORRUPT',
           "The registry is corrupted. The structure of one of the files containing registry data is corrupted, or the system's memory image of the file is corrupted, or the file could not be recovered because the alternate copy or log was absent or corrupted."),
 '1016 ': ('ERROR_REGISTRY_IO_FAILED',
           "An I/O operation initiated by the registry failed unrecoverably. The registry could not read in, or write out, or flush, one of the files that contain the system's image of the registry."),
 '1017 ': ('ERROR_NOT_REGISTRY_FILE',
           'The system has attempted to load or restore a file into the registry, but the specified file is not in a registry file format.'),
 '1018 ': ('ERROR_KEY_DELETED',
           'Illegal operation attempted on a registry key that has been marked for deletion.'),
 '1019 ': ('ERROR_NO_LOG_SPACE',
           'System could not allocate the required space in a registry log.'),
 '102': ('ERR_SOURCE_EXISTS',
         "Error: The data-source '%0' already exists and cannot be created or modified."),
 '1020 ': ('ERROR_KEY_HAS_CHILDREN',
           'Cannot create a symbolic link in a registry key that already has subkeys or values.'),
 '1021 ': ('ERROR_CHILD_MUST_BE_VOLATILE',
           'Cannot create a stable subkey under a volatile parent key.'),
 '1022 ': ('ERROR_NOTIFY_ENUM_DIR',
           "A notify change request is being completed and the information is not being returned in the caller's buffer. The caller now needs to enumerate the files to find the changes."),
 '1051 ': ('ERROR_DEPENDENT_SERVICES_RUNNING',
           'A stop control has been sent to a service that other running services are dependent on.'),
 '1052 ': ('ERROR_INVALID_SERVICE_CONTROL',
           'The requested control is not valid for this service.'),
 '1053 ': ('ERROR_SERVICE_REQUEST_TIMEOUT',
           'The service did not respond to the start or control request in a timely fashion.'),
 '1054 ': ('ERROR_SERVICE_NO_THREAD',
           'A thread could not be created for the service.'),
 '1055 ': ('ERROR_SERVICE_DATABASE_LOCKED', 'The service database is locked.'),
 '1056 ': ('ERROR_SERVICE_ALREADY_RUNNING',
           'An instance of the service is already running.'),
 '1057 ': ('ERROR_INVALID_SERVICE_ACCOUNT',
           'The account name is invalid or does not exist, or the password is invalid for the account name specified.'),
 '1058 ': ('ERROR_SERVICE_DISABLED',
           'The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.'),
 '1059 ': ('ERROR_CIRCULAR_DEPENDENCY',
           'Circular service dependency was specified.'),
 '1060 ': ('ERROR_SERVICE_DOES_NOT_EXIST',
           'The specified service does not exist as an installed service.'),
 '1061 ': ('ERROR_SERVICE_CANNOT_ACCEPT_CTRL',
           'The service cannot accept control messages at this time.'),
 '1062 ': ('ERROR_SERVICE_NOT_ACTIVE', 'The service has not been started.'),
 '1063 ': ('ERROR_FAILED_SERVICE_CONTROLLER_CONNECT',
           'The service process could not connect to the service controller.'),
 '1064 ': ('ERROR_EXCEPTION_IN_SERVICE',
           'An exception occurred in the service when handling the control request.'),
 '1065 ': ('ERROR_DATABASE_DOES_NOT_EXIST',
           'The database specified does not exist.'),
 '1066 ': ('ERROR_SERVICE_SPECIFIC_ERROR',
           'The service has returned a service-specific error code.'),
 '1067 ': ('ERROR_PROCESS_ABORTED', 'The process terminated unexpectedly.'),
 '1068 ': ('ERROR_SERVICE_DEPENDENCY_FAIL',
           'The dependency service or group failed to start.'),
 '1069 ': ('ERROR_SERVICE_LOGON_FAILED',
           'The service did not start due to a logon failure.'),
 '1070 ': ('ERROR_SERVICE_START_HANG',
           'After starting, the service hung in a start-pending state.'),
 '1071 ': ('ERROR_INVALID_SERVICE_LOCK',
           'The specified service database lock is invalid.'),
 '1072 ': ('ERROR_SERVICE_MARKED_FOR_DELETE',
           'The specified service has been marked for deletion.'),
 '1073 ': ('ERROR_SERVICE_EXISTS', 'The specified service already exists.'),
 '1074 ': ('ERROR_ALREADY_RUNNING_LKG',
           'The system is currently running with the last-known-good configuration.'),
 '1075 ': ('ERROR_SERVICE_DEPENDENCY_DELETED',
           'The dependency service does not exist or has been marked for deletion.'),
 '1076 ': ('ERROR_BOOT_ALREADY_ACCEPTED',
           'The current boot has already been accepted for use as the last-known-good control set.'),
 '1077 ': ('ERROR_SERVICE_NEVER_STARTED',
           'No attempts to start the service have been made since the last boot.'),
 '1078 ': ('ERROR_DUPLICATE_SERVICE_NAME',
           'The name is already in use as either a service name or a service display name.'),
 '1079 ': ('ERROR_DIFFERENT_SERVICE_ACCOUNT',
           'The account specified for this service is different from the account specified for other services running in the same process.'),
 '1080 ': ('ERROR_CANNOT_DETECT_DRIVER_FAILURE',
           'Failure actions can only be set for Win32 services, not for drivers.'),
 '1081 ': ('ERROR_CANNOT_DETECT_PROCESS_ABORT',
           "This service runs in the same process as the service control manager. Therefore, the service control manager cannot take action if this service's process terminates unexpectedly."),
 '1082 ': ('ERROR_NO_RECOVERY_PROGRAM',
           'No recovery program has been configured for this service.'),
 '1083 ': ('ERROR_SERVICE_NOT_IN_EXE',
           'The executable program that this service is configured to run in does not implement the service.'),
 '1084 ': ('ERROR_NOT_SAFEBOOT_SERVICE',
           'This service cannot be started in Safe Mode'),
 '110': ('ERR_CATALOG_EXISTS', "Catalog '%0' already exists."),
 '1100 ': ('ERROR_END_OF_MEDIA',
           'The physical end of the tape has been reached.'),
 '1101 ': ('ERROR_FILEMARK_DETECTED', 'A tape access reached a filemark.'),
 '1102 ': ('ERROR_BEGINNING_OF_MEDIA',
           'The beginning of the tape or a partition was encountered.'),
 '1103 ': ('ERROR_SETMARK_DETECTED',
           'A tape access reached the end of a set of files.'),
 '1104 ': ('ERROR_NO_DATA_DETECTED', 'No more data is on the tape.'),
 '1105 ': ('ERROR_PARTITION_FAILURE', 'Tape could not be partitioned.'),
 '1106 ': ('ERROR_INVALID_BLOCK_LENGTH',
           'When accessing a new tape of a multivolume partition, the current block size is incorrect.'),
 '1107 ': ('ERROR_DEVICE_NOT_PARTITIONED',
           'Tape partition information could not be found when loading a tape.'),
 '1108 ': ('ERROR_UNABLE_TO_LOCK_MEDIA',
           'Unable to lock the media eject mechanism.'),
 '1109 ': ('ERROR_UNABLE_TO_UNLOAD_MEDIA', 'Unable to unload the media.'),
 '1110 ': ('ERROR_MEDIA_CHANGED', 'The media in the drive may have changed.'),
 '1111 ': ('ERROR_BUS_RESET', 'The I/O bus was reset.'),
 '1112 ': ('ERROR_NO_MEDIA_IN_DRIVE', 'No media in drive.'),
 '1113 ': ('ERROR_NO_UNICODE_TRANSLATION',
           'No mapping for the Unicode character exists in the target multi-byte code page.'),
 '1114 ': ('ERROR_DLL_INIT_FAILED',
           'A dynamic link library (DLL) initialization routine failed.'),
 '1115 ': ('ERROR_SHUTDOWN_IN_PROGRESS', 'A system shutdown is in progress.'),
 '1116 ': ('ERROR_NO_SHUTDOWN_IN_PROGRESS',
           'Unable to abort the system shutdown because no shutdown was in progress.'),
 '1117 ': ('ERROR_IO_DEVICE',
           'The request could not be performed because of an I/O device error.'),
 '1118 ': ('ERROR_SERIAL_NO_DEVICE',
           'No serial device was successfully initialized. The serial driver will unload.'),
 '1119 ': ('ERROR_IRQ_BUSY',
           'Unable to open a device that was sharing an interrupt request (IRQ) with other devices. At least one other device that uses that IRQ was already opened.'),
 '1120 ': ('ERROR_MORE_WRITES',
           'A serial I/O operation was completed by another write to the serial port. The IOCTL_SERIAL_XOFF_COUNTER reached zero.)'),
 '1121 ': ('ERROR_COUNTER_TIMEOUT',
           'A serial I/O operation completed because the timeout period expired. The IOCTL_SERIAL_XOFF_COUNTER did not reach zero.)'),
 '1122 ': ('ERROR_FLOPPY_ID_MARK_NOT_FOUND',
           'No ID address mark was found on the floppy disk.'),
 '1123 ': ('ERROR_FLOPPY_WRONG_CYLINDER',
           'Mismatch between the floppy disk sector ID field and the floppy disk controller track address.'),
 '1124 ': ('ERROR_FLOPPY_UNKNOWN_ERROR',
           'The floppy disk controller reported an error that is not recognized by the floppy disk driver.'),
 '1125 ': ('ERROR_FLOPPY_BAD_REGISTERS',
           'The floppy disk controller returned inconsistent results in its registers.'),
 '1126 ': ('ERROR_DISK_RECALIBRATE_FAILED',
           'While accessing the hard disk, a recalibrate operation failed, even after retries.'),
 '1127 ': ('ERROR_DISK_OPERATION_FAILED',
           'While accessing the hard disk, a disk operation failed even after retries.'),
 '1128 ': ('ERROR_DISK_RESET_FAILED',
           'While accessing the hard disk, a disk controller reset was needed, but even that failed.'),
 '1129 ': ('ERROR_EOM_OVERFLOW', 'Physical end of tape encountered.'),
 '1130 ': ('ERROR_NOT_ENOUGH_SERVER_MEMORY',
           'Not enough server storage is available to process this command.'),
 '1131 ': ('ERROR_POSSIBLE_DEADLOCK',
           'A potential deadlock condition has been detected.'),
 '1132 ': ('ERROR_MAPPED_ALIGNMENT',
           'The base address or the file offset specified does not have the proper alignment.'),
 '1140 ': ('ERROR_SET_POWER_STATE_VETOED',
           'An attempt to change the system power state was vetoed by another application or driver.'),
 '1141 ': ('ERROR_SET_POWER_STATE_FAILED',
           'The system BIOS failed an attempt to change the system power state.'),
 '1142 ': ('ERROR_TOO_MANY_LINKS',
           'An attempt was made to create more links on a file than the file system supports.'),
 '1150 ': ('ERROR_OLD_WIN_VERSION',
           'The specified program requires a newer version of Windows.'),
 '1151 ': ('ERROR_APP_WRONG_OS',
           'The specified program is not a Windows or MS-DOS program.'),
 '1152 ': ('ERROR_SINGLE_INSTANCE_APP',
           'Cannot start more than one instance of the specified program.'),
 '1153 ': ('ERROR_RMODE_APP',
           'The specified program was written for an earlier version of Windows.'),
 '1154 ': ('ERROR_INVALID_DLL',
           'One of the library files needed to run this application is damaged.'),
 '1155 ': ('ERROR_NO_ASSOCIATION',
           'No application is associated with the specified file for this operation.'),
 '1156 ': ('ERROR_DDE_FAIL',
           'An error occurred in sending the command to the application.'),
 '1157 ': ('ERROR_DLL_NOT_FOUND',
           'One of the library files needed to run this application cannot be found.'),
 '1158 ': ('ERROR_NO_MORE_USER_HANDLES',
           'The current process has used all of its system allowance of handles for Window Manager objects.'),
 '1159 ': ('ERROR_MESSAGE_SYNC_ONLY',
           'The message can be used only with synchronous operations.'),
 '116': ('ERR_CATALOG_NOTFOUND', "Cannot find catalog '%0'."),
 '1160 ': ('ERROR_SOURCE_ELEMENT_EMPTY',
           'The indicated source element has no media.'),
 '1161 ': ('ERROR_DESTINATION_ELEMENT_FULL',
           'The indicated destination element already contains media.'),
 '1162 ': ('ERROR_ILLEGAL_ELEMENT_ADDRESS',
           'The indicated element does not exist.'),
 '1163 ': ('ERROR_MAGAZINE_NOT_PRESENT',
           'The indicated element is part of a magazine that is not present.'),
 '1164 ': ('ERROR_DEVICE_REINITIALIZATION_NEEDED',
           'The indicated device requires reinitialization due to hardware errors.'),
 '1165 ': ('ERROR_DEVICE_REQUIRES_CLEANING',
           'The device has indicated that cleaning is required before further operations are attempted.'),
 '1166 ': ('ERROR_DEVICE_DOOR_OPEN',
           'The device has indicated that its door is open.'),
 '1167 ': ('ERROR_DEVICE_NOT_CONNECTED', 'The device is not connected.'),
 '1168 ': ('ERROR_NOT_FOUND', 'Element not found.'),
 '1169 ': ('ERROR_NO_MATCH',
           'There was no match for the specified key in the index.'),
 '1170 ': ('ERROR_SET_NOT_FOUND',
           'The property set specified does not exist on the object.'),
 '1171 ': ('ERROR_POINT_NOT_FOUND',
           'The point passed to GetMouseMovePoints is not in the buffer.'),
 '1172 ': ('ERROR_NO_TRACKING_SERVICE',
           'The tracking (workstation) service is not running.'),
 '1173 ': ('ERROR_NO_VOLUME_ID', 'The Volume ID could not be found.'),
 '1175 ': ('ERROR_UNABLE_TO_REMOVE_REPLACED',
           'Unable to remove the file to be replaced.'),
 '1176 ': ('ERROR_UNABLE_TO_MOVE_REPLACEMENT',
           'Unable to move the replacement file to the file to be replaced. The file to be replaced has retained its original name.'),
 '1177 ': ('ERROR_UNABLE_TO_MOVE_REPLACEMENT_2',
           'Unable to move the replacement file to the file to be replaced. The file to be replaced has been renamed using the backup name.'),
 '1178 ': ('ERROR_JOURNAL_DELETE_IN_PROGRESS',
           'The volume change journal is being deleted.'),
 '1179 ': ('ERROR_JOURNAL_NOT_ACTIVE',
           'The volume change journal is not active.'),
 '1180 ': ('ERROR_POTENTIAL_FILE_FOUND',
           'A file was found, but it may not be the correct file.'),
 '1181 ': ('ERROR_JOURNAL_ENTRY_DELETED',
           'The journal entry has been deleted from the journal.'),
 '119': ('ERR_MEMBER_EXISTS',
         "Profile-member '%1' cannot be created. A property or group named '%0' already exists within the profile."),
 '1190 ': ('ERROR_SHUTDOWN_IS_SCHEDULED',
           'A system shutdown has already been scheduled.'),
 '1191 ': ('ERROR_SHUTDOWN_USERS_LOGGED_ON',
           'The system shutdown cannot be initiated because there are other users logged on to the computer.'),
 '120': ('ERR_INVALID_TYPEDEF',
         "The data type '%1' for source member '%0' is invalid."),
 '1200 ': ('ERROR_BAD_DEVICE', 'The specified device name is invalid.'),
 '1201 ': ('ERROR_CONNECTION_UNAVAIL',
           'The device is not currently connected but it is a remembered connection.'),
 '1202 ': ('ERROR_DEVICE_ALREADY_REMEMBERED',
           'The local device name has a remembered connection to another network resource.'),
 '1203 ': ('ERROR_NO_NET_OR_BAD_PATH',
           'The network path was either typed incorrectly, does not exist, or the network provider is not currently available. Please try retyping the path or contact your network administrator.'),
 '1204 ': ('ERROR_BAD_PROVIDER',
           'The specified network provider name is invalid.'),
 '1205 ': ('ERROR_CANNOT_OPEN_PROFILE',
           'Unable to open the network connection profile.'),
 '1206 ': ('ERROR_BAD_PROFILE',
           'The network connection profile is corrupted.'),
 '1207 ': ('ERROR_NOT_CONTAINER', 'Cannot enumerate a noncontainer.'),
 '1208 ': ('ERROR_EXTENDED_ERROR', 'An extended error has occurred.'),
 '1209 ': ('ERROR_INVALID_GROUPNAME',
           'The format of the specified group name is invalid.'),
 '121': ('ERR_CATALOG_DELETEFAILED',
         "Cannot delete catalog '%0'. Source: '%1' Reason: '%2'"),
 '1210 ': ('ERROR_INVALID_COMPUTERNAME',
           'The format of the specified computer name is invalid.'),
 '1211 ': ('ERROR_INVALID_EVENTNAME',
           'The format of the specified event name is invalid.'),
 '1212 ': ('ERROR_INVALID_DOMAINNAME',
           'The format of the specified domain name is invalid.'),
 '1213 ': ('ERROR_INVALID_SERVICENAME',
           'The format of the specified service name is invalid.'),
 '1214 ': ('ERROR_INVALID_NETNAME',
           'The format of the specified network name is invalid.'),
 '1215 ': ('ERROR_INVALID_SHARENAME',
           'The format of the specified share name is invalid.'),
 '1216 ': ('ERROR_INVALID_PASSWORDNAME',
           'The format of the specified password is invalid.'),
 '1217 ': ('ERROR_INVALID_MESSAGENAME',
           'The format of the specified message name is invalid.'),
 '1218 ': ('ERROR_INVALID_MESSAGEDEST',
           'The format of the specified message destination is invalid.'),
 '1219 ': ('ERROR_SESSION_CREDENTIAL_CONFLICT',
           'Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again.'),
 '122': ('ERR_XML_PARSE',
         "Parse errors in XML document '%0', line %1, col %2. Reason: %3"),
 '1220 ': ('ERROR_REMOTE_SESSION_LIMIT_EXCEEDED',
           'An attempt was made to establish a session to a network server, but there are already too many sessions established to that server.'),
 '1221 ': ('ERROR_DUP_DOMAINNAME',
           'The workgroup or domain name is already in use by another computer on the network.'),
 '1222 ': ('ERROR_NO_NETWORK', 'The network is not present or not started.'),
 '1223 ': ('ERROR_CANCELLED', 'The operation was canceled by the user.'),
 '1224 ': ('ERROR_USER_MAPPED_FILE',
           'The requested operation cannot be performed on a file with a user-mapped section open.'),
 '1225 ': ('ERROR_CONNECTION_REFUSED',
           'The remote computer refused the network connection.'),
 '1226 ': ('ERROR_GRACEFUL_DISCONNECT',
           'The network connection was gracefully closed.'),
 '1227 ': ('ERROR_ADDRESS_ALREADY_ASSOCIATED',
           'The network transport endpoint already has an address associated with it.'),
 '1228 ': ('ERROR_ADDRESS_NOT_ASSOCIATED',
           'An address has not yet been associated with the network endpoint.'),
 '1229 ': ('ERROR_CONNECTION_INVALID',
           'An operation was attempted on a nonexistent network connection.'),
 '1230 ': ('ERROR_CONNECTION_ACTIVE',
           'An invalid operation was attempted on an active network connection.'),
 '1231 ': ('ERROR_NETWORK_UNREACHABLE',
           'The network location cannot be reached. For information about network troubleshooting, see Windows Help.'),
 '1232 ': ('ERROR_HOST_UNREACHABLE',
           'The network location cannot be reached. For information about network troubleshooting, see Windows Help.'),
 '1233 ': ('ERROR_PROTOCOL_UNREACHABLE',
           'The network location cannot be reached. For information about network troubleshooting, see Windows Help.'),
 '1234 ': ('ERROR_PORT_UNREACHABLE',
           'No service is operating at the destination network endpoint on the remote system.'),
 '1235 ': ('ERROR_REQUEST_ABORTED', 'The request was aborted.'),
 '1236 ': ('ERROR_CONNECTION_ABORTED',
           'The network connection was aborted by the local system.'),
 '1237 ': ('ERROR_RETRY',
           'The operation could not be completed. A retry should be performed.'),
 '1238 ': ('ERROR_CONNECTION_COUNT_LIMIT',
           'A connection to the server could not be made because the limit on the number of concurrent connections for this account has been reached.'),
 '1239 ': ('ERROR_LOGIN_TIME_RESTRICTION',
           'Attempting to log in during an unauthorized time of day for this account.'),
 '1240 ': ('ERROR_LOGIN_WKSTA_RESTRICTION',
           'The account is not authorized to log in from this station.'),
 '1241 ': ('ERROR_INCORRECT_ADDRESS',
           'The network address could not be used for the operation requested.'),
 '1242 ': ('ERROR_ALREADY_REGISTERED', 'The service is already registered.'),
 '1243 ': ('ERROR_SERVICE_NOT_FOUND', 'The specified service does not exist.'),
 '1244 ': ('ERROR_NOT_AUTHENTICATED',
           'The operation being requested was not performed because the user has not been authenticated.'),
 '1245 ': ('ERROR_NOT_LOGGED_ON',
           'The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist.'),
 '1246 ': ('ERROR_CONTINUE', 'Continue with work in progress.'),
 '1247 ': ('ERROR_ALREADY_INITIALIZED',
           'An attempt was made to perform an initialization operation when initialization has already been completed.'),
 '1248 ': ('ERROR_NO_MORE_DEVICES', 'No more local devices.'),
 '1249 ': ('ERROR_NO_SUCH_SITE', 'The specified site does not exist.'),
 '125': ('ERR_MEMBER_NOT_GROUP',
         "The profile-member corresponding to group '%0' in the XML document is not a group."),
 '1250 ': ('ERROR_DOMAIN_CONTROLLER_EXISTS',
           'A domain controller with the specified name already exists.'),
 '1251 ': ('ERROR_ONLY_IF_CONNECTED',
           'This operation is supported only when you are connected to the server.'),
 '1252 ': ('ERROR_OVERRIDE_NOCHANGES',
           'The group policy framework should call the extension even if there are no changes.'),
 '1253 ': ('ERROR_BAD_USER_PROFILE',
           'The specified user does not have a valid profile.'),
 '1254 ': ('ERROR_NOT_SUPPORTED_ON_SBS',
           'This operation is not supported on a computer running Windows Server 2003 for Small Business Server'),
 '1255 ': ('ERROR_SERVER_SHUTDOWN_IN_PROGRESS',
           'The server machine is shutting down.'),
 '1256 ': ('ERROR_HOST_DOWN',
           'The remote system is not available. For information about network troubleshooting, see Windows Help.'),
 '1257 ': ('ERROR_NON_ACCOUNT_SID',
           'The security identifier provided is not from an account domain.'),
 '1258 ': ('ERROR_NON_DOMAIN_SID',
           'The security identifier provided does not have a domain component.'),
 '1259 ': ('ERROR_APPHELP_BLOCK',
           'AppHelp dialog canceled thus preventing the application from starting.'),
 '126': ('ERR_COLUMN_NOTFOUND', "The data-member '%0' could not be found."),
 '1260 ': ('ERROR_ACCESS_DISABLED_BY_POLICY',
           'This program is blocked by group policy. For more information, contact your system administrator.'),
 '1261 ': ('ERROR_REG_NAT_CONSUMPTION',
           'A program attempt to use an invalid register value. Normally caused by an uninitialized register. This error is Itanium specific.'),
 '1262 ': ('ERROR_CSCSHARE_OFFLINE',
           'The share is currently offline or does not exist.'),
 '1263 ': ('ERROR_PKINIT_FAILURE',
           'The Kerberos protocol encountered an error while validating the KDC certificate during smartcard logon. There is more information in the system event log.'),
 '1264 ': ('ERROR_SMARTCARD_SUBSYSTEM_FAILURE',
           'The Kerberos protocol encountered an error while attempting to utilize the smartcard subsystem.'),
 '1265 ': ('ERROR_DOWNGRADE_DETECTED',
           'The system detected a possible attempt to compromise security. Please ensure that you can contact the server that authenticated you.'),
 '127': ('ERR_COLUMN_EXISTS', "The data-member '%0' already exists."),
 '1271 ': ('ERROR_MACHINE_LOCKED',
           'The machine is locked and cannot be shut down without the force option.'),
 '1273 ': ('ERROR_CALLBACK_SUPPLIED_INVALID_DATA',
           'An application-defined callback gave invalid data when called.'),
 '1274 ': ('ERROR_SYNC_FOREGROUND_REFRESH_REQUIRED',
           'The group policy framework should call the extension in the synchronous foreground policy refresh.'),
 '1275 ': ('ERROR_DRIVER_BLOCKED',
           'This driver has been blocked from loading'),
 '1276 ': ('ERROR_INVALID_IMPORT_OF_NON_DLL',
           "A dynamic link library (DLL) referenced a module that was neither a DLL nor the process's executable image."),
 '1277 ': ('ERROR_ACCESS_DISABLED_WEBBLADE',
           'Windows cannot open this program since it has been disabled.'),
 '1278 ': ('ERROR_ACCESS_DISABLED_WEBBLADE_TAMPER',
           'Windows cannot open this program because the license enforcement system has been tampered with or become corrupted.'),
 '1279 ': ('ERROR_RECOVERY_FAILURE', 'A transaction recover failed.'),
 '1280 ': ('ERROR_ALREADY_FIBER',
           'The current thread has already been converted to a fiber.'),
 '1281 ': ('ERROR_ALREADY_THREAD',
           'The current thread has already been converted from a fiber.'),
 '1282 ': ('ERROR_STACK_BUFFER_OVERRUN',
           'The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.'),
 '1283 ': ('ERROR_PARAMETER_QUOTA_EXCEEDED',
           'Data present in one of the parameters is more than the function can operate on.'),
 '1284 ': ('ERROR_DEBUGGER_INACTIVE',
           'An attempt to do an operation on a debug object failed because the object is in the process of being deleted.'),
 '1285 ': ('ERROR_DELAY_LOAD_FAILED',
           'An attempt to delay-load a .dll or get a function address in a delay-loaded .dll failed.'),
 '1286 ': ('ERROR_VDM_DISALLOWED',
           '%1 is a 16-bit application. You do not have permissions to execute 16-bit applications. Check your permissions with your system administrator.'),
 '1287 ': ('ERROR_UNIDENTIFIED_ERROR',
           'Insufficient information exists to identify the cause of failure.'),
 '1288 ': ('ERROR_INVALID_CRUNTIME_PARAMETER',
           'The parameter passed to a C runtime function is incorrect.'),
 '1289 ': ('ERROR_BEYOND_VDL',
           'The operation occurred beyond the valid data length of the file.'),
 '129': ('ERR_MEMBER_NOTFOUND', "The profile-member '%0' could not be found."),
 '1290 ': ('ERROR_INCOMPATIBLE_SERVICE_SID_TYPE',
           'The service start failed since one or more services in the same process have an incompatible service SID type setting. A service with restricted service SID type can only coexist in the same process with other services with a restricted SID type. If the service SID type for this service was just configured, the hosting process must be restarted in order to start this service.'),
 '1291 ': ('ERROR_DRIVER_PROCESS_TERMINATED',
           'The process hosting the driver for this device has been terminated.'),
 '1292 ': ('ERROR_IMPLEMENTATION_LIMIT',
           'An operation attempted to exceed an implementation-defined limit.'),
 '1293 ': ('ERROR_PROCESS_IS_PROTECTED',
           "Either the target process, or the target thread's containing process, is a protected process."),
 '1294 ': ('ERROR_SERVICE_NOTIFY_CLIENT_LAGGING',
           'The service notification client is lagging too far behind the current state of services in the machine.'),
 '1295 ': ('ERROR_DISK_QUOTA_EXCEEDED',
           'The requested file operation failed because the storage quota was exceeded. To free up disk space, move files to a different location or delete unnecessary files. For more information, contact your system administrator.'),
 '1296 ': ('ERROR_CONTENT_BLOCKED',
           'The requested files operation failed because the storage policy blocks that type of file. For more information, contact your system administrator.'),
 '1297 ': ('ERROR_INCOMPATIBLE_SERVICE_PRIVILEGE',
           'A privilege that the service requires to function properly does not exist in the service account configuration. You may use the Services Microsoft Management Console (MMC) snap-in (services.msc) and the Local Security Settings MMC snap-in (secpol.msc) to view the service configuration and the account configuration.'),
 '1299 ': ('ERROR_INVALID_LABEL',
           'Indicates a particular Security ID may not be assigned as the label of an object.'),
 '130': ('ERR_TABLE_EXISTS',
         "The data-object '%0' already exists. (Source '%1', Catalog '%2'.)"),
 '1300': ('ERROR_NOT_ALL_ASSIGNED',
          'Not all privileges or groups referenced are assigned to the caller.'),
 '1301': ('ERROR_SOME_NOT_MAPPED',
          'Some mapping between account names and security IDs was not done.'),
 '1302': ('ERROR_NO_QUOTAS_FOR_ACCOUNT',
          'No system quota limits are specifically set for this account.'),
 '1303': ('ERROR_LOCAL_USER_SESSION_KEY',
          'No encryption key is available. A well-known encryption key was returned.'),
 '1304': ('ERROR_NULL_LM_PASSWORD',
          'The password is too complex to be converted to a LAN Manager password. The LAN Manager password returned is a NULL string.'),
 '1305': ('ERROR_UNKNOWN_REVISION', 'The revision level is unknown.'),
 '1306': ('ERROR_REVISION_MISMATCH',
          'Indicates two revision levels are incompatible.'),
 '1307': ('ERROR_INVALID_OWNER',
          'This security ID may not be assigned as the owner of this object.'),
 '1308': ('ERROR_INVALID_PRIMARY_GROUP',
          'This security ID may not be assigned as the primary group of an object.'),
 '1309': ('ERROR_NO_IMPERSONATION_TOKEN',
          'An attempt has been made to operate on an impersonation token by a thread that is not currently impersonating a client.'),
 '131': ('ERR_TABLE_NOTFOUND',
         "The data-object '%0' could not be found. (Source '%1', Catalog '%2'.)"),
 '1310': ('ERROR_CANT_DISABLE_MANDATORY', 'The group may not be disabled.'),
 '1311': ('ERROR_NO_LOGON_SERVERS',
          'There are currently no logon servers available to service the logon request.'),
 '1312': ('ERROR_NO_SUCH_LOGON_SESSION',
          'A specified logon session does not exist. It may already have been terminated.'),
 '1313': ('ERROR_NO_SUCH_PRIVILEGE', 'A specified privilege does not exist.'),
 '1314': ('ERROR_PRIVILEGE_NOT_HELD',
          'A required privilege is not held by the client.'),
 '1315': ('ERROR_INVALID_ACCOUNT_NAME',
          'The name provided is not a properly formed account name.'),
 '1316': ('ERROR_USER_EXISTS', 'The specified account already exists.'),
 '1317': ('ERROR_NO_SUCH_USER', 'The specified account does not exist.'),
 '1318': ('ERROR_GROUP_EXISTS', 'The specified group already exists.'),
 '1319': ('ERROR_NO_SUCH_GROUP', 'The specified group does not exist.'),
 '1320': ('ERROR_MEMBER_IN_GROUP',
          'Either the specified user account is already a member of the specified group, or the specified group cannot be deleted because it contains a member.'),
 '1321': ('ERROR_MEMBER_NOT_IN_GROUP',
          'The specified user account is not a member of the specified group account.'),
 '1322': ('ERROR_LAST_ADMIN',
          'The last remaining administration account cannot be disabled or deleted.'),
 '1323': ('ERROR_WRONG_PASSWORD',
          'Unable to update the password. The value provided as the current password is incorrect.'),
 '1324': ('ERROR_ILL_FORMED_PASSWORD',
          'Unable to update the password. The value provided for the new password contains values that are not allowed in passwords.'),
 '1325': ('ERROR_PASSWORD_RESTRICTION',
          'Unable to update the password. The value provided for the new password does not meet the length, complexity, or history requirements of the domain.'),
 '1326': ('ERROR_LOGON_FAILURE',
          'Logon failure: unknown user name or bad password.'),
 '1327': ('ERROR_ACCOUNT_RESTRICTION',
          'Logon failure: user account restriction. Possible reasons are blank passwords not allowed, logon hour restrictions, or a policy restriction has been enforced.'),
 '1328': ('ERROR_INVALID_LOGON_HOURS',
          'Logon failure: account logon time restriction violation.'),
 '1329': ('ERROR_INVALID_WORKSTATION',
          'Logon failure: user not allowed to log on to this computer.'),
 '133': ('ERR_ATTRIBUTE_EXISTS',
         "Duplicate names are not allowed: '%0' already exists on '%1'."),
 '1330': ('ERROR_PASSWORD_EXPIRED',
          'Logon failure: the specified account password has expired.'),
 '1331': ('ERROR_ACCOUNT_DISABLED',
          'Logon failure: account currently disabled.'),
 '1332': ('ERROR_NONE_MAPPED',
          'No mapping between account names and security IDs was done.'),
 '1333': ('ERROR_TOO_MANY_LUIDS_REQUESTED',
          'Too many local user identifiers (LUIDs) were requested at one time.'),
 '1334': ('ERROR_LUIDS_EXHAUSTED',
          'No more local user identifiers (LUIDs) are available.'),
 '1335': ('ERROR_INVALID_SUB_AUTHORITY',
          'The subauthority part of a security ID is invalid for this particular use.'),
 '1336': ('ERROR_INVALID_ACL',
          'The access control list (ACL) structure is invalid.'),
 '1337': ('ERROR_INVALID_SID', 'The security ID structure is invalid.'),
 '1338': ('ERROR_INVALID_SECURITY_DESCR',
          'The security descriptor structure is invalid.'),
 '1340': ('ERROR_BAD_INHERITANCE_ACL',
          'The inherited access control list (ACL) or access control entry (ACE) could not be built.'),
 '1341': ('ERROR_SERVER_DISABLED', 'The server is currently disabled.'),
 '1342': ('ERROR_SERVER_NOT_DISABLED', 'The server is currently enabled.'),
 '1343': ('ERROR_INVALID_ID_AUTHORITY',
          'The value provided was an invalid value for an identifier authority.'),
 '1344': ('ERROR_ALLOTTED_SPACE_EXCEEDED',
          'No more memory is available for security information updates.'),
 '1345': ('ERROR_INVALID_GROUP_ATTRIBUTES',
          'The specified attributes are invalid, or incompatible with the attributes for the group as a whole.'),
 '1346': ('ERROR_BAD_IMPERSONATION_LEVEL',
          'Either a required impersonation level was not provided, or the provided impersonation level is invalid.'),
 '1347': ('ERROR_CANT_OPEN_ANONYMOUS',
          'Cannot open an anonymous level security token.'),
 '1348': ('ERROR_BAD_VALIDATION_CLASS',
          'The validation information class requested was invalid.'),
 '1349': ('ERROR_BAD_TOKEN_TYPE',
          'The type of the token is inappropriate for its attempted use.'),
 '135': ('ERR_NO_SRCINFOS',
         "No source-infos were specified for data-source '%0'."),
 '1350': ('ERROR_NO_SECURITY_ON_OBJECT',
          'Unable to perform a security operation on an object that has no associated security.'),
 '1351': ('ERROR_CANT_ACCESS_DOMAIN_INFO',
          'Configuration information could not be read from the domain controller, either because the machine is unavailable, or access has been denied.'),
 '1352': ('ERROR_INVALID_SERVER_STATE',
          'The security account manager (SAM) or local security authority (LSA) server was in the wrong state to perform the security operation.'),
 '1353': ('ERROR_INVALID_DOMAIN_STATE',
          'The domain was in the wrong state to perform the security operation.'),
 '1354': ('ERROR_INVALID_DOMAIN_ROLE',
          'This operation is only allowed for the Primary Domain Controller of the domain.'),
 '1355': ('ERROR_NO_SUCH_DOMAIN',
          'The specified domain either does not exist or could not be contacted.'),
 '1356': ('ERROR_DOMAIN_EXISTS', 'The specified domain already exists.'),
 '1357': ('ERROR_DOMAIN_LIMIT_EXCEEDED',
          'An attempt was made to exceed the limit on the number of domains per server.'),
 '1358': ('ERROR_INTERNAL_DB_CORRUPTION',
          'Unable to complete the requested operation because of either a catastrophic media failure or a data structure corruption on the disk.'),
 '1359': ('ERROR_INTERNAL_ERROR', 'An internal error occurred.'),
 '136': ('ERR_TOO_MANY_SRCINFOS',
         "More than one source-info is specified for non-partitioned data-source '%0'. A non-partitioned data source may only have one source-info."),
 '1360': ('ERROR_GENERIC_NOT_MAPPED',
          'Generic access types were contained in an access mask which should already be mapped to nongeneric types.'),
 '1361': ('ERROR_BAD_DESCRIPTOR_FORMAT',
          'A security descriptor is not in the right format (absolute or self-relative).'),
 '1362': ('ERROR_NOT_LOGON_PROCESS',
          'The requested action is restricted for use by logon processes only. The calling process has not registered as a logon process.'),
 '1363': ('ERROR_LOGON_SESSION_EXISTS',
          'Cannot start a new logon session with an ID that is already in use.'),
 '1364': ('ERROR_NO_SUCH_PACKAGE',
          'A specified authentication package is unknown.'),
 '1365': ('ERROR_BAD_LOGON_SESSION_STATE',
          'The logon session is not in a state that is consistent with the requested operation.'),
 '1366': ('ERROR_LOGON_SESSION_COLLISION',
          'The logon session ID is already in use.'),
 '1367': ('ERROR_INVALID_LOGON_TYPE',
          'A logon request contained an invalid logon type value.'),
 '1368': ('ERROR_CANNOT_IMPERSONATE',
          'Unable to impersonate using a named pipe until data has been read from that pipe.'),
 '1369': ('ERROR_RXACT_INVALID_STATE',
          'The transaction state of a registry subtree is incompatible with the requested operation.'),
 '137': ('ERR_NOT_ONE_DEFAULT_SRCINFO',
         "One source-info must be marked as default for data-source '%0'."),
 '1370': ('ERROR_RXACT_COMMIT_FAILURE',
          'An internal security database corruption has been encountered.'),
 '1371': ('ERROR_SPECIAL_ACCOUNT',
          'Cannot perform this operation on built-in accounts.'),
 '1372': ('ERROR_SPECIAL_GROUP',
          'Cannot perform this operation on this built-in special group.'),
 '1373': ('ERROR_SPECIAL_USER',
          'Cannot perform this operation on this built-in special user.'),
 '1374': ('ERROR_MEMBERS_PRIMARY_GROUP',
          "The user cannot be removed from a group because the group is currently the user's primary group."),
 '1375': ('ERROR_TOKEN_ALREADY_IN_USE',
          'The token is already in use as a primary token.'),
 '1376': ('ERROR_NO_SUCH_ALIAS', 'The specified local group does not exist.'),
 '1377': ('ERROR_MEMBER_NOT_IN_ALIAS',
          'The specified account name is not a member of the group.'),
 '1378': ('ERROR_MEMBER_IN_ALIAS',
          'The specified account name is already a member of the group.'),
 '1379': ('ERROR_ALIAS_EXISTS', 'The specified local group already exists.'),
 '138': ('ERR_SRCINFO_NOTFOUND',
         "The source-info '%1' could not be found in data-source '%0'."),
 '1380': ('ERROR_LOGON_NOT_GRANTED',
          'Logon failure: the user has not been granted the requested logon type at this computer.'),
 '1381': ('ERROR_TOO_MANY_SECRETS',
          'The maximum number of secrets that may be stored in a single system has been exceeded.'),
 '1382': ('ERROR_SECRET_TOO_LONG',
          'The length of a secret exceeds the maximum length allowed.'),
 '1383': ('ERROR_INTERNAL_DB_ERROR',
          'The local security authority database contains an internal inconsistency.'),
 '1384': ('ERROR_TOO_MANY_CONTEXT_IDS',
          "During a logon attempt, the user's security context accumulated too many security IDs."),
 '1385': ('ERROR_LOGON_TYPE_NOT_GRANTED',
          'Logon failure: the user has not been granted the requested logon type at this computer.'),
 '1386': ('ERROR_NT_CROSS_ENCRYPTION_REQUIRED',
          'A cross-encrypted password is necessary to change a user password.'),
 '1387': ('ERROR_NO_SUCH_MEMBER',
          'A member could not be added to or removed from the local group because the member does not exist.'),
 '1388': ('ERROR_INVALID_MEMBER',
          'A new member could not be added to a local group because the member has the wrong account type.'),
 '1389': ('ERROR_TOO_MANY_SIDS', 'Too many security IDs have been specified.'),
 '1390': ('ERROR_LM_CROSS_ENCRYPTION_REQUIRED',
          'A cross-encrypted password is necessary to change this user password.'),
 '1391': ('ERROR_NO_INHERITANCE',
          'Indicates an ACL contains no inheritable components.'),
 '1392': ('ERROR_FILE_CORRUPT',
          'The file or directory is corrupted and unreadable.'),
 '1393': ('ERROR_DISK_CORRUPT',
          'The disk structure is corrupted and unreadable.'),
 '1394': ('ERROR_NO_USER_SESSION_KEY',
          'There is no user session key for the specified logon session.'),
 '1395': ('ERROR_LICENSE_QUOTA_EXCEEDED',
          'The service being accessed is licensed for a particular number of connections. No more connections can be made to the service at this time because there are already as many connections as the service can accept.'),
 '1396': ('ERROR_WRONG_TARGET_NAME',
          'Logon Failure: The target account name is incorrect.'),
 '1397': ('ERROR_MUTUAL_AUTH_FAILED',
          "Mutual Authentication failed. The server's password is out of date at the domain controller."),
 '1398': ('ERROR_TIME_SKEW',
          'There is a time and/or date difference between the client and server.'),
 '1399': ('ERROR_CURRENT_DOMAIN_NOT_ALLOWED',
          'This operation cannot be performed on the current domain.'),
 '1400': ('ERROR_INVALID_WINDOW_HANDLE', 'Invalid window handle.'),
 '1401': ('ERROR_INVALID_MENU_HANDLE', 'Invalid menu handle.'),
 '1402': ('ERROR_INVALID_CURSOR_HANDLE', 'Invalid cursor handle.'),
 '1403': ('ERROR_INVALID_ACCEL_HANDLE', 'Invalid accelerator table handle.'),
 '1404': ('ERROR_INVALID_HOOK_HANDLE', 'Invalid hook handle.'),
 '1405': ('ERROR_INVALID_DWP_HANDLE',
          'Invalid handle to a multiple-window position structure.'),
 '1406': ('ERROR_TLW_WITH_WSCHILD', 'Cannot create a top-level child window.'),
 '1407': ('ERROR_CANNOT_FIND_WND_CLASS', 'Cannot find window class.'),
 '1408': ('ERROR_WINDOW_OF_OTHER_THREAD',
          'Invalid window; it belongs to other thread.'),
 '1409': ('ERROR_HOTKEY_ALREADY_REGISTERED', 'Hot key is already registered.'),
 '141': ('ERR_MULTIPLE_RDNATTRS',
         "The profile '%0' contains multiple properties marked as the RDN Attribute for the data source '%1'. Exactly one RDN Attribute must be defined for each LDAPv3-compliant data source."),
 '1410': ('ERROR_CLASS_ALREADY_EXISTS', 'Class already exists.'),
 '1411': ('ERROR_CLASS_DOES_NOT_EXIST', 'Class does not exist.'),
 '1412': ('ERROR_CLASS_HAS_WINDOWS', 'Class still has open windows.'),
 '1413': ('ERROR_INVALID_INDEX', 'Invalid index.'),
 '1414': ('ERROR_INVALID_ICON_HANDLE', 'Invalid icon handle.'),
 '1415': ('ERROR_PRIVATE_DIALOG_INDEX', 'Using private DIALOG window words.'),
 '1416': ('ERROR_LISTBOX_ID_NOT_FOUND',
          'The list box identifier was not found.'),
 '1417': ('ERROR_NO_WILDCARD_CHARACTERS', 'No wildcards were found.'),
 '1418': ('ERROR_CLIPBOARD_NOT_OPEN',
          'Thread does not have a clipboard open.'),
 '1419': ('ERROR_HOTKEY_NOT_REGISTERED', 'Hot key is not registered.'),
 '142': ('ERR_MULTIPLE_HASHKEYS',
         "The profile '%0' contains multiple properties marked as the hashing key."),
 '1420': ('ERROR_WINDOW_NOT_DIALOG',
          'The window is not a valid dialog window.'),
 '1421': ('ERROR_CONTROL_ID_NOT_FOUND', 'Control ID not found.'),
 '1422': ('ERROR_INVALID_COMBOBOX_MESSAGE',
          'Invalid message for a combo box because it does not have an edit control.'),
 '1423': ('ERROR_WINDOW_NOT_COMBOBOX', 'The window is not a combo box.'),
 '1424': ('ERROR_INVALID_EDIT_HEIGHT', 'Height must be less than 256.'),
 '1425': ('ERROR_DC_NOT_FOUND', 'Invalid device context (DC) handle.'),
 '1426': ('ERROR_INVALID_HOOK_FILTER', 'Invalid hook procedure type.'),
 '1427': ('ERROR_INVALID_FILTER_PROC', 'Invalid hook procedure.'),
 '1428': ('ERROR_HOOK_NEEDS_HMOD',
          'Cannot set nonlocal hook without a module handle.'),
 '1429': ('ERROR_GLOBAL_ONLY_HOOK',
          'This hook procedure can only be set globally.'),
 '143': ('ERR_INVALID_RDNATTR',
         "The profile-property '%0' is marked as an RDN-attribute, but does not map to an LDAPv3-compliant data-source."),
 '1430': ('ERROR_JOURNAL_HOOK_SET',
          'The journal hook procedure is already installed.'),
 '1431': ('ERROR_HOOK_NOT_INSTALLED', 'The hook procedure is not installed.'),
 '1432': ('ERROR_INVALID_LB_MESSAGE',
          'Invalid message for single-selection list box.'),
 '1433': ('ERROR_SETCOUNT_ON_BAD_LB',
          'LB_SETCOUNT sent to non-lazy list box.'),
 '1434': ('ERROR_LB_WITHOUT_TABSTOPS',
          'This list box does not support tab stops.'),
 '1435': ('ERROR_DESTROY_OBJECT_OF_OTHER_THREAD',
          'Cannot destroy object created by another thread.'),
 '1436': ('ERROR_CHILD_WINDOW_MENU', 'Child windows cannot have menus.'),
 '1437': ('ERROR_NO_SYSTEM_MENU', 'The window does not have a system menu.'),
 '1438': ('ERROR_INVALID_MSGBOX_STYLE', 'Invalid message box style.'),
 '1439': ('ERROR_INVALID_SPI_VALUE', 'Invalid system-wide (SPI_*) parameter.'),
 '144': ('ERR_PROP_INVALID_HASHKEY',
         "The profile-property '%0' is marked as a hashing-key, but does not map to any partitioned data-sources."),
 '1440': ('ERROR_SCREEN_ALREADY_LOCKED', 'Screen already locked.'),
 '1441': ('ERROR_HWNDS_HAVE_DIFF_PARENT',
          'All handles to windows in a multiple-window position structure must have the same parent.'),
 '1442': ('ERROR_NOT_CHILD_WINDOW', 'The window is not a child window.'),
 '1443': ('ERROR_INVALID_GW_COMMAND', 'Invalid GW_* command.'),
 '1444': ('ERROR_INVALID_THREAD_ID', 'Invalid thread identifier.'),
 '1445': ('ERROR_NON_MDICHILD_WINDOW',
          'Cannot process a message from a window that is not a multiple document interface (MDI) window.'),
 '1446': ('ERROR_POPUP_ALREADY_ACTIVE', 'Popup menu already active.'),
 '1447': ('ERROR_NO_SCROLLBARS', 'The window does not have scroll bars.'),
 '1448': ('ERROR_INVALID_SCROLLBAR_RANGE',
          'Scroll bar range cannot be greater than MAXLONG.'),
 '1449': ('ERROR_INVALID_SHOWWIN_COMMAND',
          'Cannot show or remove the window in the way specified.'),
 '145': ('ERR_NO_RDN_ATTRIBUTE',
         "The profile '%0' uses an LDAPv3-compliant data-source, but no property is marked as the RDN-attribute. Exactly one RDN Attribute must be defined for each LDAPv3-compliant data source."),
 '1450': ('ERROR_NO_SYSTEM_RESOURCES',
          'Insufficient system resources exist to complete the requested service.'),
 '1451': ('ERROR_NONPAGED_SYSTEM_RESOURCES',
          'Insufficient system resources exist to complete the requested service.'),
 '1452': ('ERROR_PAGED_SYSTEM_RESOURCES',
          'Insufficient system resources exist to complete the requested service.'),
 '1453': ('ERROR_WORKING_SET_QUOTA',
          'Insufficient quota to complete the requested service.'),
 '1454': ('ERROR_PAGEFILE_QUOTA',
          'Insufficient quota to complete the requested service.'),
 '1455': ('ERROR_COMMITMENT_LIMIT',
          'The paging file is too small for this operation to complete.'),
 '1456': ('ERROR_MENU_ITEM_NOT_FOUND', 'A menu item was not found.'),
 '1457': ('ERROR_INVALID_KEYBOARD_HANDLE', 'Invalid keyboard layout handle.'),
 '1458': ('ERROR_HOOK_TYPE_NOT_ALLOWED', 'Hook type not allowed.'),
 '1459': ('ERROR_REQUIRES_INTERACTIVE_WINDOWSTATION',
          'This operation requires an interactive window station.'),
 '1460': ('ERROR_TIMEOUT',
          'This operation returned because the timeout period expired.'),
 '1461': ('ERROR_INVALID_MONITOR_HANDLE', 'Invalid monitor handle.'),
 '1462': ('ERROR_INCORRECT_SIZE', 'Incorrect size argument.'),
 '1463': ('ERROR_SYMLINK_CLASS_DISABLED',
          'The symbolic link cannot be followed because its type is disabled.'),
 '1464': ('ERROR_SYMLINK_NOT_SUPPORTED',
          'This application does not support the current operation on symbolic links.'),
 '1465': ('ERROR_XML_PARSE_ERROR',
          'Windows was unable to parse the requested XML data.'),
 '1466': ('ERROR_XMLDSIG_ERROR',
          'An error was encountered while processing an XML digital signature.'),
 '1467': ('ERROR_RESTART_APPLICATION', 'This application must be restarted.'),
 '1468': ('ERROR_WRONG_COMPARTMENT',
          'The caller made the connection request in the wrong routing compartment.'),
 '1469': ('ERROR_AUTHIP_FAILURE',
          'There was an AuthIP failure when attempting to connect to the remote host.'),
 '1500': ('ERROR_EVENTLOG_FILE_CORRUPT', 'The event log file is corrupted.'),
 '1501': ('ERROR_EVENTLOG_CANT_START',
          'No event log file could be opened, so the event logging service did not start.'),
 '1502': ('ERROR_LOG_FILE_FULL', 'The event log file is full.'),
 '1503': ('ERROR_EVENTLOG_FILE_CHANGED',
          'The event log file has changed between read operations.'),
 '1550': ('ERROR_INVALID_TASK_NAME', 'The specified task name is invalid.'),
 '1551': ('ERROR_INVALID_TASK_INDEX', 'The specified task index is invalid.'),
 '1552': ('ERROR_THREAD_ALREADY_IN_TASK',
          'The specified thread is already joining a task.'),
 '1601': ('ERROR_INSTALL_SERVICE_FAILURE',
          'The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.'),
 '1602': ('ERROR_INSTALL_USEREXIT', 'User canceled installation.'),
 '1603': ('ERROR_INSTALL_FAILURE', 'Fatal error during installation.'),
 '1604': ('ERROR_INSTALL_SUSPEND', 'Installation suspended, incomplete.'),
 '1605': ('ERROR_UNKNOWN_PRODUCT',
          'This action is only valid for products that are currently installed.'),
 '1606': ('ERROR_UNKNOWN_FEATURE', 'Feature ID not registered.'),
 '1607': ('ERROR_UNKNOWN_COMPONENT', 'Component ID not registered.'),
 '1608': ('ERROR_UNKNOWN_PROPERTY', 'Unknown property.'),
 '1609': ('ERROR_INVALID_HANDLE_STATE', 'A handle is in an invalid state.'),
 '1610': ('ERROR_BAD_CONFIGURATION',
          'The configuration data for this product is corrupt. Contact your support personnel.'),
 '1611': ('ERROR_INDEX_ABSENT', 'Component qualifier not present.'),
 '1612': ('ERROR_INSTALL_SOURCE_ABSENT',
          'The installation source for this product is not available. Verify that the source exists and that you can access it.'),
 '1613': ('ERROR_INSTALL_PACKAGE_VERSION',
          'This installation package cannot be installed by the Windows Installer service. You must install a Windows service pack that contains a newer version of the Windows Installer service.'),
 '1614': ('ERROR_PRODUCT_UNINSTALLED', 'Product is uninstalled.'),
 '1615': ('ERROR_BAD_QUERY_SYNTAX',
          'SQL query syntax invalid or unsupported.'),
 '1616': ('ERROR_INVALID_FIELD', 'Record field does not exist.'),
 '1617': ('ERROR_DEVICE_REMOVED', 'The device has been removed.'),
 '1618': ('ERROR_INSTALL_ALREADY_RUNNING',
          'Another installation is already in progress. Complete that installation before proceeding with this install.'),
 '1619': ('ERROR_INSTALL_PACKAGE_OPEN_FAILED',
          'This installation package could not be opened. Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package.'),
 '162': ('ERR_MEMBER_INVALID_NEWDELETE',
         "One or more profile-members have invalid attributes: isNew='1' and isDeleted='1'."),
 '1620': ('ERROR_INSTALL_PACKAGE_INVALID',
          'This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer package.'),
 '1621': ('ERROR_INSTALL_UI_FAILURE',
          'There was an error starting the Windows Installer service user interface. Contact your support personnel.'),
 '1622': ('ERROR_INSTALL_LOG_FAILURE',
          'Error opening installation log file. Verify that the specified log file location exists and that you can write to it.'),
 '1623': ('ERROR_INSTALL_LANGUAGE_UNSUPPORTED',
          'The language of this installation package is not supported by your system.'),
 '1624': ('ERROR_INSTALL_TRANSFORM_FAILURE',
          'Error applying transforms. Verify that the specified transform paths are valid.'),
 '1625': ('ERROR_INSTALL_PACKAGE_REJECTED',
          'This installation is forbidden by system policy. Contact your system administrator.'),
 '1626': ('ERROR_FUNCTION_NOT_CALLED', 'Function could not be executed.'),
 '1627': ('ERROR_FUNCTION_FAILED', 'Function failed during execution.'),
 '1628': ('ERROR_INVALID_TABLE', 'Invalid or unknown table specified.'),
 '1629': ('ERROR_DATATYPE_MISMATCH', 'Data supplied is of wrong type.'),
 '1630': ('ERROR_UNSUPPORTED_TYPE', 'Data of this type is not supported.'),
 '1631': ('ERROR_CREATE_FAILED',
          'The Windows Installer service failed to start. Contact your support personnel.'),
 '1632': ('ERROR_INSTALL_TEMP_UNWRITABLE',
          'The Temp folder is on a drive that is full or is inaccessible. Free up space on the drive or verify that you have write permission on the Temp folder.'),
 '1633': ('ERROR_INSTALL_PLATFORM_UNSUPPORTED',
          'This installation package is not supported by this processor type. Contact your product vendor.'),
 '1634': ('ERROR_INSTALL_NOTUSED', 'Component not used on this computer.'),
 '1635': ('ERROR_PATCH_PACKAGE_OPEN_FAILED',
          'This update package could not be opened. Verify that the update package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer update package.'),
 '1636': ('ERROR_PATCH_PACKAGE_INVALID',
          'This update package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer update package.'),
 '1637': ('ERROR_PATCH_PACKAGE_UNSUPPORTED',
          'This update package cannot be processed by the Windows Installer service. You must install a Windows service pack that contains a newer version of the Windows Installer service.'),
 '1638': ('ERROR_PRODUCT_VERSION',
          'Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel.'),
 '1639': ('ERROR_INVALID_COMMAND_LINE',
          'Invalid command line argument. Consult the Windows Installer SDK for detailed command line help.'),
 '164': ('ERR_MEMBER_INVALID_NEWMODIFIED',
         "One or more profile-members have invalid attributes: isNew='1' and isModified='1'."),
 '1640': ('ERROR_INSTALL_REMOTE_DISALLOWED',
          'Only administrators have permission to add, remove, or configure server software during a Terminal services remote session. If you want to install or configure software on the server, contact your network administrator.'),
 '1641': ('ERROR_SUCCESS_REBOOT_INITIATED',
          'The requested operation completed successfully. The system will be restarted so the changes can take effect.'),
 '1642': ('ERROR_PATCH_TARGET_NOT_FOUND',
          'The upgrade cannot be installed by the Windows Installer service because the program to be upgraded may be missing, or the upgrade may update a different version of the program. Verify that the program to be upgraded exists on your computer and that you have the correct upgrade.'),
 '1643': ('ERROR_PATCH_PACKAGE_REJECTED',
          'The update package is not permitted by software restriction policy.'),
 '1644': ('ERROR_INSTALL_TRANSFORM_REJECTED',
          'One or more customizations are not permitted by software restriction policy.'),
 '1645': ('ERROR_INSTALL_REMOTE_PROHIBITED',
          'The Windows Installer does not permit installation from a Remote Desktop Connection.'),
 '1646': ('ERROR_PATCH_REMOVAL_UNSUPPORTED',
          'Uninstallation of the update package is not supported.'),
 '1647': ('ERROR_UNKNOWN_PATCH', 'The update is not applied to this product.'),
 '1648': ('ERROR_PATCH_NO_SEQUENCE',
          'No valid sequence could be found for the set of updates.'),
 '1649': ('ERROR_PATCH_REMOVAL_DISALLOWED',
          'Update removal was disallowed by policy.'),
 '1650': ('ERROR_INVALID_PATCH_XML', 'The XML update data is invalid.'),
 '1651': ('ERROR_PATCH_MANAGED_ADVERTISED_PRODUCT',
          'Windows Installer does not permit updating of managed advertised products. At least one feature of the product must be installed before applying the update.'),
 '1652': ('ERROR_INSTALL_SERVICE_SAFEBOOT',
          'The Windows Installer service is not accessible in Safe Mode. Please try again when your computer is not in Safe Mode or you can use System Restore to return your machine to a previous good state.'),
 '168': ('ERR_ATTRIBUTE_INVALIDNAME',
         "The attribute '%0' cannot be created because the attribute name contains invalid characters: %1"),
 '169': ('ERR_SOURCE_INVALIDNAME',
         "The data source '%0' cannot be created because the source name contains invalid characters: %1"),
 '171': ('ERR_PRIMARYKEY',
         "Profile '%0' could not be created/updated because it does not have exactly one primary key defined."),
 '172': ('ERR_JOINKEY',
         "Profile '%0' could not be created/updated because it does not have exactly one join key defined."),
 '173': ('ERR_INVALIDTYPE_RDNATTR',
         "The profile-property '%0' is marked as an RDN-attribute, but is not of type 'STRING'."),
 '174': ('ERR_INVALID_HASHKEY',
         "The profile-property '%0' is marked as a hashing key, but is not of type 'STRING'."),
 '175': ('ERR_INVALID_UNIQUEKEY',
         "The profile-property '%0' is marked as a unique, primary, and/or join key, but is not of type 'STRING' or 'NUMBER'."),
 '176': ('ERR_SOURCE_INVALIDTYPE', "'%0' is not a valid source type."),
 '177': ('ERR_TABLE_INVALIDNAME',
         "The data object '%0' cannot be created because the object name contains invalid characters: %1"),
 '178': ('ERR_SRCINFO_SRCTYPE',
         "The source type of data-source '%0' cannot be modified."),
 '179': ('ERR_INVALIDMAP',
         "The profile property '%0' is mapped to a data member in a source which is not referenced by the join key."),
 '180': ('ERR_DUPLICATEJOINMAP',
         "The join key '%0' references more than one data member from a single source. A join key may map to only one member from a data object."),
 '181': ('ERR_CACHEDPROP_IS_PRIMARYKEY',
         'The primary key for this profile may not be a cached (non-persistent) property.'),
 '182': ('ERR_CACHEDPROP_IS_JOINKEY',
         'The join key for this profile may not be a cached (non-persistent) property.'),
 '183': ('ERR_INVALID_TYPEDEF_FOR_SOURCE',
         "The data type '%1' for source member '%0' is invalid (data type invalid for source type '%2')."),
 '184': ('ERR_VALUE_TOO_LONG',
         "The database field '%0' cannot be updated. The value '%1' exceeds the maximum length of %2 characters."),
 '186': ('ERR_TOO_MANY_PARTITIONS',
         "The data source '%0' contains %1 partitions. A single data source cannot have more than %2 partitions."),
 '187': ('ERR_KEY_MULTIVALUE',
         "The property '%0' cannot be multi-valued because it is a key."),
 '188': ('ERR_OLEDB_MULTIVAL',
         "The property '%0' cannot be marked as multi-valued. It references a data member from an OLEDB-ANSI source of type '%1'. Only members of type 'STRING' may be marked as multi-valued."),
 '189': ('ERR_DUPLICATE_SOURCENAME',
         "A data-source already exists with the name '%0'."),
 '190': ('ERR_DUPLICATE_PARTITIONNAME',
         "A data-source partition already exists with the name '%0'."),
 '191': ('ERR_NOCONNECTION',
         'No connection is open to the database. The Connect() method should be called first.'),
 '192': ('ERR_INVALID_DATATYPE',
         'The property: [%0] in profile: [%1] is mapped to an incorrect data type.'),
 '193': ('ERR_INVALID_MARKEDTYPEREF',
         'The property: [%0] in profile: [%1] is incorrectly marked as a reference type.'),
 '194': ('ERR_INVALID_MULTI',
         'The property: [%0] in profile: [%1] is incorrectly marked as multivalued.'),
 '195': ('ERR_INVALID_TYPEREF',
         'The property: [%0] in profile: [%1] is referencing an invalid type.'),
 '196': ('ERR_INVALID_PROPTYPE',
         'The property: [%0] in profile: [%1] is of incorrect type.'),
 '197': ('ERR_INVALID_MAPPEDDATA',
         'The property: [%0] in profile: [%1] is mapped to a data member: [%2] but this data member does not exist.'),
 '198': ('ERR_INVALID_MAPPEDDATATYPE',
         'The property: [%0] in profile: [%1] is mapped to data member: [%2] of incorrect type'),
 '199': ('ERR_INVALID_PROFILEREF',
         'The property: [%0] in profile: [%1] is referencing a profile: [%2] that does not exist.'),
 '200': ('ERR_INVALID_SITETERMREF',
         'The property: [%0] in profile: [%1] is referencing a siteterm: [%2] that does not exist.'),
 '203': ('ERR_BAD_NAMESPACE',
         'The XML does not contain the correct namespace.'),
 '204': ('ERR_INVALID_CATALOG_NAME', "The catalog '%0' is an invalid name."),
 '205': ('ERR_MISSING_CATALOG', 'The file does not contain any catalogs.')
 }
 
class WinCollector(Base):

    configCycleInterval = 20.

    initialServices = ['EventService', 'WmiConfig']
    attributes = ('configCycleInterval',)

    heartbeat = dict(eventClass=Heartbeat, device=getfqdn())
    deviceConfig = 'getDeviceWinInfo'

    def __init__(self):
        self.heartbeat['component'] = self.agent
        self.wmiprobs = []
        Base.__init__(self)
        self.reconfigureTimeout = None


    def start(self):
        self.heartbeat['component']=self.agent
        self.log.info("Starting %s", self.agent)
        self.sendEvent(dict(summary='Starting %s' % self.agent,
                            eventClass=App_Start,
                            device=getfqdn(),
                            severity=Clear,
                            agent=self.agent,
                            component=self.agent))

    def remote_notifyConfigChanged(self):
        self.log.info("Async config notification")
        if self.reconfigureTimeout and not self.reconfigureTimeout.called:
            self.reconfigureTimeout.cancel()
        self.reconfigureTimeout = reactor.callLater(5, drive, self.reconfigure)

    def remote_deleteDevice(self):
        pass

    def processLoop(self):
        pass


    def startScan(self, unused=None):
        drive(self.scanCycle)


    def scanCycle(self, driver):
        now = time.time()
        try:
            yield self.eventService().callRemote('getWmiConnIssues')
            self.wmiprobs = [e[0] for e in driver.next()]
            self.log.debug("Wmi Probs %r", self.wmiprobs)
            self.processLoop()
            self.heartbeat['timeout'] = self.cycleInterval() * 3
            self.sendEvent(self.heartbeat)
        except Exception, ex:
            self.log.exception("Error processing main loop")
        delay = time.time() - now
        if self.options.cycle:
            driveLater(max(0, self.cycleInterval() - delay), self.scanCycle)
        else:
            self.stop()

    def stop(self):
        self.log.info("Starting %s", self.agent)
        self.sendEvent(dict(summary='Stopping %s' % self.agent,
                            eventClass=App_Stop,
                            device=getfqdn(),
                            severity=Warning,
                            component=self.agent))
        reactor.callLater(1, reactor.stop)

    def cycleInterval(self):
        return 60
        
    def buildOptions(self):
        Base.buildOptions(self)
        self.parser.add_option('-d', '--device', 
                               dest='device', 
                               default=None,
                               help="single device to collect")
        self.parser.add_option('--debug', 
                               dest='debug', 
                               default=False,
                               help="turn on additional debugging")


    def configService(self):
        return self.services.get('WmiConfig', FakeRemote())


    def updateDevices(self, cfg):
        pass


    def updateConfig(self, cfg):
        cfg = dict(cfg)
        for attribute in self.attributes:
            current = getattr(self, attribute, None)
            value = cfg.get(attribute)
            if current is not None and current != value:
                self.log.info("Setting %s to %r", attribute, value);
                setattr(self, attribute, value)

    def error(self, why):
        why.printTraceback()
        self.log.error(why.getErrorMessage())


    def reconfigure(self, driver):
        try:
            yield self.eventService().callRemote('getWmiConnIssues')
            self.wmiprobs = [e[0] for e in driver.next()]
            self.log.debug("Wmi Probs %r", self.wmiprobs)
            yield self.configService().callRemote('getConfig')
            self.updateConfig(driver.next())
            yield self.configService().callRemote(self.deviceConfig)
            self.updateDevices(driver.next())
        except Exception, ex:
            self.log.exception("Error fetching config")


    def startConfigCycle(self):
        def driveAgain(result):
            driveLater(self.configCycleInterval * 60, self.reconfigure)
            return result
        return drive(self.reconfigure).addBoth(driveAgain)

    def connected(self):
        d = self.startConfigCycle()
        d.addCallback(self.startScan)
        
    def parseComError(self, ex):
        match = re.search('com_error\((?P<code>[0-9]*)\).*', str(ex))
        if match:
            code = match.group('code')
            if ERROR_CODE_MAP.has_key(code):
                return (code,) + ERROR_CODE_MAP[code]
            else:
                return (code, None, None)
        else:
            return (None, None, None)
            
    def printComErrorMessage(self, ex):
        code, error, msg = self.parseComError(ex)
        if code and error and msg:
            return '%s: %s: %s' % (code, error, msg)
        elif code:
            return '%s: Could not map this code to a com_error'
        else:
            return None
        

